import {mountWorldExtra,extraCSS} from './world-extra.js';
import {DISPLAY_DEFAULTS} from './display-settings.js';
import {mountActionChoice} from './actions.js';
import {mountHeartBlock,mountAuditBlock,replyControlsCSS} from './reply-details.js';
import {formatProse,proseCSS} from './prose.js';
import {inspectMessage,readerErrorText,readerErrorCode} from './reader.js';
import {parseDisplayEnvelope,strictJSON} from './reader-core.js';
import {waterStyle} from './visual-theme.js';
import {visualAssets,motionManifest,journeyArt,journeyIcons} from './visual-assets.js';
import {createWaterMotion,mountPendantRack,CHAT_DEFAULTS} from './visual-core.js';
const adaptation=`:host{display:block;max-width:100%;min-width:0;background:transparent;font:17px/1.85 TisyaReading,serif;color:#e3e6d8}.page{width:100%;max-width:900px;min-width:0;padding:0 0 14px;background:transparent;box-shadow:none}.story{font:17px/1.85 TisyaReading,serif;letter-spacing:.02em;overflow-wrap:anywhere;word-break:normal}.story :is(img,video,svg){max-width:100%;height:auto}.story :is(pre,table){max-width:100%;overflow:auto}.story pre{white-space:pre-wrap}.story-region{padding:12px 4px 4px}.task-region{margin:8px 0 0;padding:10px 12px 12px}.task-masthead .hero-text{position:static;padding:0;min-width:0}.task-masthead .hero-text h1{font-size:21px;line-height:1.55;letter-spacing:.06em;color:#dfc88d;white-space:normal;overflow-wrap:anywhere}.task-masthead .hero-text p{font-size:12px;line-height:1.6;color:#a8c4b6}.task-identity{min-width:0;max-width:calc(100% - 44px)}.task-masthead{position:relative;isolation:isolate;min-height:46px;padding:0;border:0}.visual-creatures{height:62px;display:flex;align-items:center;justify-content:flex-end;gap:18px;padding-right:8px}.visual-creature{position:relative!important;inset:auto!important;transform:none!important;width:70px!important;height:50px!important;padding:0!important;border:0!important;background:none!important;min-height:44px}.visual-creature canvas,.visual-creature img{display:block;width:100%;height:100%;object-fit:contain;pointer-events:none}.visual-creature:focus-visible{outline:1px solid #dec986;border-radius:20px}.public-note{font:13px/1.7 system-ui,sans-serif;color:#adc5b6;margin:8px 0;overflow-wrap:anywhere}.action-region{padding:6px 0 10px}.action-heading h2{font-size:21px;letter-spacing:.06em}.action .text{font:15px/1.7 TisyaReading,serif;text-align:left}.action .number{font-size:20px}.action{padding:10px 12px;gap:12px;min-height:52px}.dateline{font-size:12px}.wave-rule{margin:10px 0 14px;width:55%}.pendant-dock{margin:12px 10px 0}.journey-region,.world-extension{margin-inline:0!important}.jr-header h2{font-size:24px}.jr-nav button{min-height:52px}.jr-nav button svg{width:20px;height:20px}.jr-subtitle,.jr-eyebrow{font:12px/1.6 system-ui}.jr-empty p{font-size:15px}.jr-skin{pointer-events:none}.scroll-sides{background:url("${visualAssets['scroll-sides.png']}") center top/100% auto repeat-y}.scroll-skin{pointer-events:none}.world-extension{container-type:inline-size}.world-extension>.crystal-scroll{min-height:max(235px,calc(50cqw + 48px))}.reading-number{display:none!important}.reading-paragraph{margin-bottom:1.2em}.reading-paragraph>div>p:last-child{margin-bottom:0}.loading-note{font:13px/1.7 system-ui;padding:12px 4px;color:#b7c9ba}button:focus-visible{outline:2px solid #dfc88d;outline-offset:2px}@media(prefers-reduced-motion:reduce){*,*::before,*::after{animation:none!important;transition:none!important}}:host([data-paused=true]) *, :host([data-paused=true]) *::after{animation-play-state:paused!important}`;
function maker(doc){return (tag,text,cls)=>{const n=doc.createElement(tag);if(text!==undefined&&text!==null)n.textContent=String(text);if(cls)n.className=cls;return n;};}
function artSkin(document,kind,scale){const make=maker(document),n=make('div',null,'jr-skin');n.setAttribute('aria-hidden','true');for(const piece of journeyArt.pieces[kind].crops){const p=make('i'),[w,h]=piece.size,[x,y]=piece.sourceRect,[sw,sh]=journeyArt.pieces[kind].sourceSize;Object.assign(p.style,{backgroundImage:`url("${visualAssets[piece.key]}")`,backgroundSize:`${w*scale}px ${h*scale}px`,width:w*scale+'px',height:h*scale+'px'});const name=piece.name;if(name.startsWith('rail-')){const edge=name.slice(5);if(edge==='top'||edge==='bottom'){p.style.left=(kind==='frame'?170:470)*scale+'px';p.style.right=p.style.left;p.style.width='auto';p.style[edge]=(edge==='top'?y:sh-y-h)*scale+'px';p.style.backgroundRepeat='repeat-x';}else{p.style.top=220*scale+'px';p.style.bottom=(kind==='frame'?220:324)*scale+'px';p.style.height='auto';p.style[edge]='0';p.style.backgroundRepeat='repeat-y';}}else if(name.startsWith('corner-')){p.style[name.endsWith('l')?'left':'right']='0';p.style[name.includes('-t')?'top':'bottom']='0';}else if(name.startsWith('diamond-')){p.style.left='50%';p.style.marginLeft=-w*scale/2+'px';p.style[name.endsWith('top')?'top':'bottom']=(name.endsWith('top')?y:sh-y-h)*scale+'px';}else{p.style[name.endsWith('left')?'left':'right']='0';p.style.top='50%';p.style.marginTop=-h*scale/2+'px';}n.append(p);}return n;}
function mountJourney(document,container,data){
 let manualTheme=false;
 const make=maker(document),root=make('div',null,'journey-reader');root.dataset.theme='night';for(const k of ['day','night'])root.style.setProperty('--jr-paper-'+k,`url("${visualAssets['jr4-paper-'+k+'.png']}")`);
 const header=make('header',null,'jr-header'),title=make('h2','记忆'),viewport=make('div',null,'jr-viewport'),nav=make('nav',null,'jr-nav');viewport.tabIndex=0;viewport.setAttribute('role','region');nav.setAttribute('aria-label','旅程页面');header.append(make('p','缇斯亚 · 旅程手记','jr-eyebrow'),title,make('p','本条消息的公开记录','jr-subtitle'));root.append(artSkin(document,'frame',.25),header,viewport,nav);container.append(root);
 const tabs=[['player','玩家','user'],['memory','记忆','book'],['characters','角色','group'],['tasks','任务','task-list'],['more','更多','ellipsis']],buttons=new Map();
 function empty(text,art){const card=make('section',null,'jr-card jr-card-ornate jr-empty');card.append(artSkin(document,'card',.18));if(art){const im=make('img',null,'jr-vignette');im.src=visualAssets['jr4-'+art+'.png'];im.alt='';card.append(im);}card.append(make('p',text));viewport.append(card);}
 function card(title,text){const c=make('section',null,'jr-card');if(title)c.append(make('h3',title));if(text)c.append(make('p',text,'jr-summary'));viewport.append(c);return c;}
 const positions=new Map();let active=null;
 function go(id){if(active)positions.set(active,viewport.scrollTop);active=id;title.textContent=tabs.find(t=>t[0]===id)[1];viewport.replaceChildren();for(const [key,b]of buttons)b.setAttribute('aria-current',key===id?'page':'false');const model=data.journey.value;
  if(id==='player'){empty('玩家档案与实时状态将在后续版本接入。','backpack');}
  else if(id==='tasks'){empty('任务页面已就位，任务功能待接入。','task-scroll');}
  else if(id==='more'){const c=card('日夜之间','选择旅程的纸色与灯光');const options=make('div',null,'jr-theme-options');for(const [k,text]of [['day','日间'],['night','夜间']]){const b=make('button',text,'jr-theme-choice');b.type='button';b.setAttribute('aria-pressed',String(root.dataset.theme===k));b.onclick=()=>{manualTheme=true;root.dataset.theme=k;options.querySelectorAll('button').forEach(n=>n.setAttribute('aria-pressed',String(n===b)));};options.append(b);}c.append(options);}
  else if(!model){empty('本条记录暂未就绪，原消息保留。',id==='memory'?'memory-letter':null);}
  else if(id==='memory'){if(!model.memories.length&&!model.changes.length)empty('这一回合，暂无可展示的记忆。','memory-letter');for(const memory of model.memories){const c=card(memory.scene?.title,memory.summary);if(memory.scene?.places?.length)c.prepend(make('p',memory.scene.places.join(' · '),'jr-meta'));if(memory.quote){const d=make('details',null,'jr-quote');d.append(make('summary','回看这一刻'),make('p',memory.quote.text,'jr-quote-text'));c.append(d);}for(const result of memory.results??[])c.append(make('p',result,'jr-meta'));if(memory.impact)c.append(make('p',memory.impact));}for(const change of model.changes){const c=card(change.object+' · '+change.field);if(change.hasNewValue)c.append(make('p',typeof change.newValue==='string'?change.newValue:JSON.stringify(change.newValue)));if(change.deleted)c.append(make('p','已移除'));if(change.reason)c.append(make('p',change.reason,'jr-meta'));}}
  else if(id==='characters'){const rows=model.characters.filter(c=>c.cognition.length);if(!rows.length)empty('相遇，会在这里留下记录。');for(const row of rows){const c=card(row.name);row.cognition.forEach(r=>c.append(make('p',r.content)));}}
  viewport.scrollTop=positions.get(id)??0;
 }
 for(const [id,label,glyph]of tabs){const b=make('button');b.type='button';b.dataset.jrTab=id;const svg=document.createElementNS('http://www.w3.org/2000/svg','svg'),p=document.createElementNS(svg.namespaceURI,'path');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('aria-hidden','true');p.setAttribute('d',journeyIcons[glyph]);svg.append(p);b.append(svg,make('span',label));b.onclick=()=>go(id);buttons.set(id,b);nav.append(b);}go('memory');
 return {refresh(values){if(!manualTheme)root.dataset.theme=values.旅程外观==='日间'?'day':'night';},capture(){return {tab:active,theme:root.dataset.theme,manualTheme,positions:[...positions, [active,viewport.scrollTop]]};},restore(state){if(!state)return;manualTheme=state.manualTheme===true;if(manualTheme&&['day','night'].includes(state.theme))root.dataset.theme=state.theme;for(const [id,scroll]of state.positions??[])if(tabs.some(t=>t[0]===id)&&Number.isFinite(scroll))positions.set(id,scroll);if(tabs.some(t=>t[0]===state.tab))go(state.tab);}};
}
export function mountMessageVisual(document,container,{source,name,formatBody,onChooseAction,getActionMode,setActionMode,getMotion=()=>true,getDisplay=()=>DISPLAY_DEFAULTS,onError=()=>{}}){
 const make=maker(document),host=make('div',null,'tisya-message-visual');container.append(host);const shadow=host.attachShadow({mode:'open'}),style=make('style');style.textContent=waterStyle+'\n'+adaptation+'\n'+proseCSS+'\n'+replyControlsCSS+'\n'+extraCSS;shadow.append(style);const root=make('main',null,'page');shadow.append(root);const data=inspectMessage(source);let alive=true,motion=null,rack=null,observer=null,visible=false,createdMotion=false;const manualFolds={};
 const task=make('section',null,'task-region'),mast=make('header',null,'task-masthead scene-heading'),identity=make('div',null,'task-identity'),hero=make('div',null,'hero-text'),heading=make('h1',name||'月潮 · 回声'),subtitle=make('p','此刻，潮声落在纸上。');hero.append(heading,subtitle);identity.append(hero);
 const lamp=make('div',null,'lamp-light'),composition=make('div',null,'lamp-composition'),im=make('img');im.src=visualAssets['lamp-scene.png'];im.alt='';const flame=make('canvas');flame.id='lamp-flame';flame.setAttribute('aria-hidden','true');composition.append(im,flame);lamp.append(composition);mast.append(identity,lamp);task.append(mast);root.append(task);const taskHeart=data.details?.value?mountHeartBlock(document,task,data.details.value.taskHeart,{label:'开篇心声'}):null;if(taskHeart)taskHeart.id='task-heart';
 let envelope=null;try{envelope=data.structured?parseDisplayEnvelope(source):null;const title=envelope&&strictJSON(envelope.blocks.title);if(typeof title?.text==='string'&&title.text.trim())heading.textContent=title.text;const meta=[title?.time,title?.place,title?.world].filter(x=>typeof x==='string'&&x.trim());if(meta.length)subtitle.textContent=meta.join(' · ');}catch{}
 const story=make('article',null,'story-region'),body=make('div',null,'story');story.append(make('div',null,'wave-rule'));if(data.body.error)body.append(make('p','正文尚未完整就绪，可在消息菜单中查看或编辑原消息。','loading-note'));else{try{const rows=data.body.paragraphs?.value;if(rows?.length){for(const p of rows){const section=make('section',null,'reading-paragraph'),text=make('div');section.append(make('span',p.id,'reading-number'));text.innerHTML=formatProse(document,p.raw,formatBody);section.append(text);body.append(section);}}else body.innerHTML=formatProse(document,data.body.value,formatBody);}catch(error){const note=make('p','正文排版暂不可用。'+readerErrorText(readerErrorCode(error)),'loading-note');note.setAttribute('role','status');body.replaceChildren(note);onError(error);}}story.append(body);root.append(story);
 const dock=make('div',null,'pendant-dock');dock.innerHTML='<div class="pendant-divider"><i></i><i></i></div><div class="pendant-hooks"></div>';root.append(dock);
 const world=make('section',null,'world-extension scroll-region'),worldLanding=make('div',null,'scroll-crest'),worldPanel=make('div',null,'crystal-scroll');worldPanel.id='world-extension-expanded';worldPanel.innerHTML=`<div class="scroll-skin"><img class="scroll-top" alt="" src="${visualAssets['scroll-top.png']}"><div class="scroll-sides"></div><img class="scroll-bottom" alt="" src="${visualAssets['scroll-bottom.png']}"></div>`;
 const worldHeader=make('header',null,'extension-heading');worldHeader.append(make('h2','世界扩展'));const worldContent=make('div',null,'extension-sheet');const extraView=mountWorldExtra(document,worldContent,{source,structured:data.structured,formatBody,onError});worldPanel.append(worldHeader,worldContent);world.append(worldLanding,worldPanel);root.append(world);
 const journey=make('section',null,'journey-region scroll-region'),journeyLanding=make('div',null,'scroll-crest'),journeyPanel=make('div',null,'dashboard');journeyPanel.id='journey-dashboard';journey.append(journeyLanding,journeyPanel);root.append(journey);const journeyView=mountJourney(document,journeyPanel,data);
 rack=mountPendantRack({root,assets:visualAssets});for(const [id,title,region,panel,landing,cover]of [['journey','旅程手记',journey,journeyPanel,journeyLanding,'journey-cover.png'],['world-extension','世界扩展',world,worldPanel,worldLanding,'cover.png']])rack.register({id,title,region,panel,landing,cover:visualAssets[cover],onToggle:value=>{if(alive){manualFolds[id]=value;rack.setExpanded(id,value,{animate:true});extraView.refresh(!getMotion());}}});
 const action=make('section',null,'action-region');if(data.details?.value)mountAuditBlock(document,action,data.details.value.audit);else if(data.details?.error)action.append(make('p','心声与核验暂不可用。'+readerErrorText(data.details.error),'loading-note'));const nextHeart=data.details?.value?mountHeartBlock(document,action,data.details.value.nextHeart,{label:'收篇心声'}):null;if(nextHeart)nextHeart.id='next-heart';const creatures=make('div',null,'visual-creatures'),actors=[];for(const [kind,label,asset]of [['jelly','轻触水母','jelly.png'],['tadpole','轻触蝌蚪','tadpole.png']]){const b=make('button',null,'creature visual-creature');b.type='button';b.setAttribute('aria-label',label);const im=make('img');im.src=visualAssets[asset];im.alt='';b.append(im);const heart=kind==='jelly'?taskHeart:nextHeart;(heart??creatures).prepend(b);actors.push({kind,node:b});}if(creatures.childElementCount)action.append(creatures);
 const actionHeading=make('div',null,'action-heading');actionHeading.append(make('h2','下一步，往哪里？'));action.append(actionHeading);let actionChoice=null;
 if(data.actions.value?.length){actionChoice=mountActionChoice(document,action,{rows:data.actions.value,onChoose:onChooseAction,getMode:getActionMode,setMode:setActionMode,quill:visualAssets['quill.png'],onError});}else action.append(make('p',data.actions.error?'行动卡界面已就位，本条建议暂未接通。':'这一页暂时没有行动建议。','public-note'));root.append(action);
 const motionError=e=>{if(alive){let note=root.querySelector('.motion-error');if(!note){note=make('p',null,'public-note motion-error');note.setAttribute('role','status');task.append(note);}note.textContent='灯火与水中小动物加载失败，请更新后重启。';onError(e);}};
 function sync(){const config=getDisplay();journeyView.refresh(config);for(const [id,key]of [['journey','旅程球默认状态'],['world-extension','世界扩展默认状态']])rack.setExpanded(id,Object.hasOwn(manualFolds,id)?manualFolds[id]:config[key]==='展开');actionChoice?.refresh();const paused=!visible||!getMotion()||document.hidden;host.dataset.paused=String(paused);rack.pause(paused);extraView.refresh(paused);if(visible&&!createdMotion){createdMotion=true;try{motion=createWaterMotion({root,lampCanvas:flame,assets:visualAssets,manifest:Object.fromEntries(['flame','jelly','tadpole'].map(k=>[k,motionManifest[k]])),onError:motionError});motion.pause(paused);for(const a of actors){const actor=motion.attach(a.node,a.kind);a.node.onclick=()=>actor.poke();}motion.ready.catch(()=>{});}catch(e){motionError(e);}}motion?.pause(paused);}
 const win=document.defaultView;if(win.IntersectionObserver){observer=new win.IntersectionObserver(entries=>{visible=entries.some(e=>e.isIntersecting);sync();},{root:document.querySelector('#chat'),rootMargin:'80px'});observer.observe(host);}else{visible=true;sync();}
 const visibility=()=>sync();document.addEventListener('visibilitychange',visibility);sync();return {host,data,refresh:sync,capture(){return {folds:{...manualFolds},journey:journeyView.capture(),extra:extraView.capture()};},restore(state){if(!state)return;for(const [k,v]of Object.entries(state.folds??{}))if(['journey','world-extension'].includes(k)&&typeof v==='boolean')manualFolds[k]=v;journeyView.restore(state.journey);extraView.restore(state.extra);sync();},dispose(){alive=false;observer?.disconnect();document.removeEventListener('visibilitychange',visibility);motion?.dispose();rack?.dispose();extraView.dispose();actionChoice?.dispose();host.remove();}};
}
export function mountMessageAppearance(document,{getMessage,formatBody,onChooseAction,getActionMode,setActionMode,getMotion=()=>true,getDisplay=()=>DISPLAY_DEFAULTS,onError=()=>{}}){
 const views=new Map(),states=new WeakMap();let alive=true;const editing=n=>n.classList.contains('editing')||!!n.querySelector('.edit_textarea');
 function restore(node){const row=views.get(node);if(!row)return;if(row.message){let saved=states.get(row.message);if(!saved){saved=new Map();states.set(row.message,saved);}saved.set(row.source,row.view.capture?.());if(saved.size>8)saved.delete(saved.keys().next().value);}row.view.dispose();row.native.classList.remove('tisya-source-concealed');node.classList.remove('tisya-projected');views.delete(node);}
 function sync(node,{pending=false}={}){if(!alive||!node?.isConnected)return;const msg=getMessage(node),native=node.querySelector('.mes_text');if(!msg||msg.is_system||!native||editing(node)){restore(node);return;}const previous=views.get(node);if(pending)return;const role=msg.is_user?'user':'assistant';if(previous?.source===msg.mes&&previous.role===role&&previous.native===native&&previous.view.host.isConnected){if(!native.classList.contains('tisya-source-concealed'))native.classList.add('tisya-source-concealed');return;}restore(node);
  // Embedded native interactive content keeps its host-owned document and listeners.
  const candidate=inspectMessage(msg.mes);if(!candidate.structured&&native.querySelector('iframe,custom-style,style,script'))return;
  // User-authored prose marks are a formatting preview, never an AI reply or a
  // state/action envelope. Unmarked input and literal protocol examples stay native.
  if(msg.is_user&&(candidate.structured||!msg.mes.includes('〔')))return;
  try{const source=msg.mes,block=node.querySelector('.mes_block')??node,options={source,name:msg.name,formatBody:text=>formatBody(text,msg,node),onChooseAction:(text,mode)=>onChooseAction(node,source,text,mode),getActionMode,setActionMode,getMotion,getDisplay,onError},view=msg.is_user?mountUserProse(document,block,options):mountMessageVisual(document,block,options);view.restore?.(states.get(msg)?.get(source));native.after(view.host);native.classList.add('tisya-source-concealed');node.classList.add('tisya-projected');views.set(node,{view,native,source:msg.mes,role,message:msg});}catch(e){native.classList.remove('tisya-source-concealed');node.querySelectorAll('.tisya-message-visual').forEach(n=>n.remove());onError(e);}
 }
 const observer=new document.defaultView.MutationObserver(records=>{for(const [n]of views)if(!n.isConnected)restore(n);const nodes=new Set();for(const r of records){if(r.type==='attributes'&&r.target.matches?.('.mes'))nodes.add(r.target);if(r.type==='childList'&&[...r.addedNodes].some(n=>n.nodeType===1&&n.matches?.('.edit_textarea')))nodes.add(r.target.closest?.('.mes'));}for(const n of nodes)if(n)sync(n);});observer.observe(document.querySelector('#chat'),{childList:true,subtree:true,attributes:true,attributeFilter:['class']});
 return {sync,restore,refresh(){for(const {view}of views.values())view.refresh();},dispose(){alive=false;observer.disconnect();for(const n of [...views.keys()])restore(n);},size:()=>views.size};
}
function mountUserProse(document,container,{source,formatBody,onError}){
 const host=document.createElement('div');host.className='tisya-message-visual';host.dataset.prosePreview='user';
 const shadow=host.attachShadow({mode:'open'}),style=document.createElement('style'),body=document.createElement('article');
 style.textContent=adaptation+'\n'+proseCSS;body.className='story';
 try{body.innerHTML=formatProse(document,source,formatBody);}catch(error){const note=document.createElement('p');note.className='loading-note';note.setAttribute('role','status');note.textContent='正文排版暂不可用。'+readerErrorText(readerErrorCode(error));body.append(note);onError(error);}
 shadow.append(style,body);container.append(host);return {host,refresh(){},dispose(){host.remove();}};
}
export function mountChatEffects(document,{getMotion=()=>true,getDisplay=()=>DISPLAY_DEFAULTS,onError=()=>{}}={}){
 const win=document.defaultView,sheld=document.querySelector('#sheld'),chat=document.querySelector('#chat'),host=document.createElement('div'),canvas=document.createElement('canvas');host.id='tisya-chat-effects';host.setAttribute('aria-hidden','true');host.append(canvas);sheld.prepend(host);let effect=null,alive=true;
 const resize=()=>{if(!alive)return;const s=sheld.getBoundingClientRect(),c=chat.getBoundingClientRect();Object.assign(host.style,{left:c.left-s.left+'px',top:c.top-s.top+'px',width:c.width+'px',height:c.height+'px'});effect?.resize();};resize();
 try{effect=createWaterMotion({root:host,canvas,assets:visualAssets,manifest:{},onError});effect.setEffects(getDisplay());effect.ready.catch(()=>{});}catch(e){onError(e);}
 let pointer=null;const down=e=>{if(e.button===0&&e.isPrimary!==false)pointer={id:e.pointerId,x:e.clientX,y:e.clientY,time:win.performance.now()};},cancel=()=>{pointer=null;},tap=e=>{if(pointer?.id===e.pointerId&&win.performance.now()-pointer.time<450&&Math.hypot(e.clientX-pointer.x,e.clientY-pointer.y)<9&&getDisplay().点触涟漪&&getMotion()&&!document.getSelection()?.toString()&&!e.composedPath().some(n=>n.matches?.('button,input,textarea,select,a,summary,dialog')))effect?.tap(e.clientX,e.clientY);pointer=null;};chat.addEventListener('pointerdown',down,{passive:true});chat.addEventListener('pointercancel',cancel);chat.addEventListener('scroll',cancel,{passive:true});chat.addEventListener('pointerup',tap,{passive:true});const observer=win.ResizeObserver?new win.ResizeObserver(resize):null;observer?.observe(chat);win.addEventListener('resize',resize);
 const refresh=()=>{effect?.setEffects(getDisplay());effect?.pause(!getMotion()||sheld.classList.contains('tisya-page-open')||document.body.querySelector('#tisya-shell.tisya-page-open')!==null);};refresh();return {refresh,report:()=>effect?.report(),dispose(){alive=false;effect?.dispose();observer?.disconnect();win.removeEventListener('resize',resize);chat.removeEventListener('pointerdown',down);chat.removeEventListener('pointercancel',cancel);chat.removeEventListener('scroll',cancel);chat.removeEventListener('pointerup',tap);host.remove();}};
}
