import {composition,renderCharacter,characterIdlePose,createCharacterReaction,decodedResourceImage} from './visual-core.js';
import {visualAssets,phoneResources,characterFrames} from './visual-assets.js';
const css=`:host{all:initial;position:fixed;display:block;z-index:65;pointer-events:none;color:#e9dfba;font:14px/1.5 system-ui,sans-serif;contain:layout style}*{box-sizing:border-box}[hidden]{display:none!important}.viewport{overflow:auto;overscroll-behavior:contain;pointer-events:none;scrollbar-width:none}.scene{position:relative;isolation:isolate;pointer-events:none}.art{position:absolute;pointer-events:none;user-select:none}.phone-face{position:absolute;z-index:5;pointer-events:none}.control,.app,.hide,.title{pointer-events:auto;position:absolute;display:grid;place-items:center;border:0;background:none;color:#efe1b4;padding:0;min-width:44px;min-height:44px;cursor:pointer;-webkit-tap-highlight-color:transparent}.control{z-index:8}.control img{width:24px;height:24px}.control[data-drag],.title{touch-action:none}.control:focus-visible,.app:focus-visible,.hide:focus-visible{outline:2px solid #edcf8d;outline-offset:0;border-radius:10px}.app{z-index:5;align-content:start;font:11px/1.35 system-ui;text-shadow:0 1px 3px #062520}.app img{object-fit:contain;width:34px;height:34px}.app span{padding-top:4px;white-space:nowrap}.title{font:14px/1.3 TisyaReading,serif;text-shadow:0 1px 4px #021e17;z-index:7;transform:translate(-50%,-50%)}.card{position:absolute;z-index:5;padding:12px;border-radius:13px;background:linear-gradient(135deg,#b6c2a528,#07352bc9);border:1px solid #c3bd8275;color:#d9d9bc;display:flex;flex-direction:column;justify-content:center}.card strong{font:18px/1.4 TisyaReading,serif;color:#ead6a1}.card p{margin:4px 0 0;font:11px/1.4 system-ui}.nav{position:absolute;border-radius:20px;background:#355c4c99;border:1px solid #cabf8033;z-index:5}.dot{position:absolute;width:4px;height:4px;border-radius:50%;background:#c9c59c65}.dot.active{background:#e9d18c}.app-page{position:absolute;z-index:6;background:#0b302be8;border:1px solid #bfba7955;border-radius:15px;padding:14px;overflow:auto;pointer-events:auto;color:#dcdcc6}.app-page img{display:block;width:64px;height:64px;object-fit:contain;margin:12px auto}.app-page h2{font:20px TisyaReading,serif;text-align:center;color:#e1c98b;margin:12px 0}.app-page p{font:13px/1.65 system-ui;margin:12px 0}.app-page button{min-height:44px;width:100%;color:inherit;border:1px solid #d5c99870;background:#244b3fc9;border-radius:10px}.hide{z-index:10;right:0;top:0;opacity:.65;border-radius:50%;width:32px;height:32px;min-width:44px;min-height:44px;font:20px system-ui}.hide:hover,.hide:focus{opacity:1;background:#12372dcc}.status{position:absolute;bottom:0;right:0;font:11px/1.4 system-ui;background:#11342fdd;border-radius:7px;padding:4px 8px;pointer-events:auto;max-width:140px}.tisha-character-reaction{position:fixed;pointer-events:none;z-index:11}.tisha-character-reaction img{position:absolute;width:100%;height:100%;object-fit:contain}.fallback{width:100%;height:100%;object-fit:contain}@media(prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}`;
export function petBounds(document){
 const w=document.defaultView,v=w.visualViewport,c=document.querySelector('#chat')?.getBoundingClientRect(),form=document.querySelector('#send_form')?.getBoundingClientRect();
 const left=Math.max(0,v?.offsetLeft??0,c?.width?c.left:0)+4,top=Math.max(v?.offsetTop??0,c?.height?c.top:0)+4;
 const right=Math.min(w.innerWidth,(v?.offsetLeft??0)+(v?.width??w.innerWidth),c?.width?c.right:w.innerWidth)-4;
 const bottom=Math.min(w.innerHeight,(v?.offsetTop??0)+(v?.height??w.innerHeight),c?.height?c.bottom:w.innerHeight,form?.height?form.top:w.innerHeight)-4;
 return {x:left,y:top,width:Math.max(1,right-left),height:Math.max(1,bottom-top)};
}
export function mountPet(document,{onError=()=>{},onVisibility=()=>{},getMotion=()=>true}={}){
 const win=document.defaultView,host=document.createElement('aside');host.id='tisya-pet';host.setAttribute('data-tt-mobile-surface','none');host.setAttribute('aria-label','缇斯亚桌宠与手机');const root=host.attachShadow({mode:'open'}),style=document.createElement('style');style.textContent=css;root.append(style);document.body.append(host);
 const make=(tag,cls,text)=>{const n=document.createElement(tag);n.className=cls;if(text)n.textContent=text;return n;},viewport=make('div','viewport'),scene=make('div','scene'),status=make('span','status');status.setAttribute('role','status');status.hidden=true;viewport.append(scene);root.append(viewport,status);
 let alive=true,shown=true,mode='standing',page=null,g,position=null,drag=null,reaction=null,epoch=0,ready=false,failed=false,canvases=[],off=[],blocked=false,lastMode=null;
 const textures={},images=new Map(),imageJobs=new Map();
 const listen=(n,event,fn,opts)=>{n?.addEventListener(event,fn,opts);off.push(()=>n?.removeEventListener(event,fn,opts));};
 async function load(key){if(images.has(key))return images.get(key);if(imageJobs.has(key))return imageJobs.get(key);const r=phoneResources[key];const p=decodedResourceImage({document,url:visualAssets[key],name:key,width:r.width,height:r.height,isAlive:()=>alive}).then(im=>{images.set(key,im);return im;}).finally(()=>imageJobs.delete(key));imageJobs.set(key,p);return p;}
 async function loadKind(kind){if(textures[kind])return;const t={};for(const expression of kind.startsWith('tail')?['neutral']:['neutral','blink','sulk']){const key=expression==='neutral'?kind:'character'+kind[0].toUpperCase()+kind.slice(1)+expression[0].toUpperCase()+expression.slice(1);const r=phoneResources[key];t[expression]={image:await load(key),width:r.width,height:r.height};}if(kind==='head'||kind==='front'){const frames={};for(const key of characterFrames.resources){const r=phoneResources[key];frames[key]={image:await load(key),width:r.width,height:r.height};}t.frames=frames;}textures[kind]=t;}
 const box=(n,r)=>Object.assign(n.style,{left:r.x+'px',top:r.y+'px',width:r.width+'px',height:r.height+'px'});
 function img(key){const n=make('img','');n.alt='';n.draggable=false;n.src=visualAssets[key];return n;}
 function paint(pose=characterIdlePose(0,true)){
  for(const {n,kind,fallback}of canvases){if(!textures[kind])continue;try{const ctx=n.getContext('2d');if(!ctx)continue;renderCharacter(ctx,textures[kind],kind,pose,n.width,n.height);fallback.hidden=true;n.hidden=false;}catch(e){fail(e);return;}}
 }
 function fail(e){if(!alive)return;failed=true;status.textContent='动画未载入 · 点此重试';status.hidden=false;reaction?.dismiss('load-error');onError(e);}
 function sceneBounds(){const b=petBounds(document);return {x:b.x,y:b.y,width:Math.max(b.width,1),height:Math.max(b.height,1)};}
 function anchor(){const r=host.getBoundingClientRect(),target=g?.controls.find(c=>c.action==='poke'||c.action==='drag-face');return {visible:shown&&!blocked&&ready&&getMotion()&&!failed,moving:!!drag,head:target?{x:r.left+target.x,y:r.top+target.y-viewport.scrollTop,width:target.width,height:target.height}:{x:r.left,y:r.top,width:80,height:60}};}
 function layout(center=false){
  if(!alive)return;const b=sceneBounds();blocked=b.height<90;host.hidden=!shown||blocked;
  const width=Math.min(g.width,b.width),height=Math.min(g.height,b.height);if(!position||center)position={x:b.x+b.width-width,y:b.y+b.height-height};
  position={x:Math.max(b.x,Math.min(position.x,b.x+b.width-width)),y:Math.max(b.y,Math.min(position.y,b.y+b.height-height))};
  Object.assign(host.style,{left:position.x+'px',top:position.y+'px',width:width+'px',height:height+'px'});Object.assign(viewport.style,{width:width+'px',height:height+'px',pointerEvents:mode==='standing'?'none':'auto'});reaction?.refresh();
 }
 function openApp(name){page=name;render(mode);}
 function request(action){if(action==='poke'||action==='drag-face'){reaction?.poke();return;}if(action==='open')render('folded',true);else if(action==='expand')render('expanded',true);else if(action==='collapse')render('folded',true);else if(action==='close'){page=null;render('standing',true);}else if(action==='home'||action==='back'){page=null;render(mode);}else if(action==='more')openApp('设置');}
 function render(next=mode,center=false){
  if(!alive)return;const ticket=++epoch;reaction?.dismiss('layout');mode=next;if(mode!=='expanded')page=null;
  const available=sceneBounds().width;g=composition(mode,Math.max(360,Math.min(412,available+8)));scene.replaceChildren();canvases=[];box(scene,{x:0,y:0,width:g.width,height:g.height});scene.dataset.mode=mode;
  for(const r of g.layers){const animated=['standing','head','front','tailExpanded','tailFolded'].includes(r.asset),layer=make('div','art');box(layer,r);layer.style.zIndex=r.asset==='front'?'6':r.asset.startsWith('frame')?'4':r.asset.startsWith('bg')?'3':r.asset==='head'?'2':'1';
   const fallback=img(r.asset);fallback.className='fallback';layer.append(fallback);if(animated){const n=make('canvas','art');const dpr=Math.min(win.devicePixelRatio||1,2);n.width=Math.ceil(r.width*dpr);n.height=Math.ceil(r.height*dpr);box(n,{x:0,y:0,width:r.width,height:r.height});n.hidden=true;layer.append(n);canvases.push({n,kind:r.asset,fallback});}scene.append(layer);
  }
  if(g.content){const c=g.content,title=make('button','title','月潮');title.type='button';title.setAttribute('aria-label','拖动手机');title.dataset.drag='title';title.style.left=c.title.x+'px';title.style.top=c.title.y+'px';scene.append(title);
   if(c.card){const card=make('div','card');box(card,c.card);card.append(make('strong','','潮声常伴'),make('p','','把旅程，收在掌心。'));scene.append(card);}
   if(c.navigationBar){const bar=make('div','nav');box(bar,c.navigationBar);scene.append(bar);}
   for(const p of c.pagination){const dot=make('i','dot'+(p.active?' active':''));dot.style.left=p.x+'px';dot.style.top=p.y+'px';scene.append(dot);}
   for(const a of [...c.apps,...c.shortcuts]){const button=make('button','app');button.type='button';button.setAttribute('aria-label',a.name);box(button,{x:a.x-22,y:a.y-17,width:44,height:a.label?56:44});button.append(img('icon'+a.name));if(a.label)button.append(make('span','',a.name));button.addEventListener('click',()=>{if(mode==='folded'){mode='expanded';}openApp(a.name);});scene.append(button);}
   if(page){const p=make('section','app-page');p.setAttribute('aria-label',page);box(p,{x:c.inner.left,y:c.frame.y+83,width:c.inner.right-c.inner.left,height:c.navigationBar.y-c.frame.y-99});p.append(img('icon'+page),make('h2','',page),make('p','','界面已就位，功能将在后续版本接入。'));const back=make('button','','返回桌面');back.type='button';back.addEventListener('click',()=>{page=null;render(mode);});p.append(back);scene.append(p);}
  }
  const names={open:'打开手机',poke:'戳戳缇斯亚',expand:'展开',collapse:'收起',close:'关闭',back:'返回',home:'主页',more:'更多','drag-face':'戳戳或拖动缇斯亚'};
  for(const c of g.controls){const n=make('button','control');n.type='button';box(n,c);n.setAttribute('aria-label',names[c.action]);n.title=names[c.action];n.dataset.action=c.action;if(['open','poke','drag-face'].includes(c.action))n.dataset.drag=c.action;else n.append(img('control'+names[c.action]));scene.append(n);}
  if(mode==='standing'){const hide=make('button','hide','×');hide.type='button';hide.title='隐藏桌宠';hide.setAttribute('aria-label','隐藏桌宠');hide.addEventListener('click',()=>setVisible(false));scene.append(hide);}
  layout(center||lastMode!==mode);lastMode=mode;paint();ready=false;status.hidden=true;failed=false;
  const kinds=[...new Set(canvases.map(c=>c.kind))];Promise.all(kinds.map(loadKind)).then(()=>{if(!alive||ticket!==epoch)return;ready=true;paint();reaction?.refresh();}).catch(e=>{if(alive&&ticket===epoch)fail(e);});
 }
 function setVisible(value){shown=!!value;layout();onVisibility(shown);}
 reaction=createCharacterReaction({container:root,assets:visualAssets,getAnchor:anchor,getBounds:sceneBounds,setFrame:(_,pose)=>paint(pose),setIdle:pose=>{for(const {n}of canvases)n.style.transform='translateY('+(pose.floatY||0)+'px)';},onError:e=>{if(e.code==='TISHA_REACTION_NO_ROOM')return;fail(e);}});
 listen(scene,'pointerdown',e=>{const target=e.target.closest('[data-drag]');if(!target||e.button!==0)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY,px:position.x,py:position.y,moved:false,target};target.setPointerCapture?.(e.pointerId);reaction?.refresh();});
 listen(scene,'pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(dx,dy)>6)drag.moved=true;if(drag.moved){position={x:drag.px+dx,y:drag.py+dy};layout();}});
 let suppressClick=false;const end=e=>{if(!drag||drag.id!==e.pointerId)return;suppressClick=drag.moved||e.type==='pointercancel';drag=null;reaction?.refresh();};listen(scene,'pointerup',end);listen(scene,'pointercancel',end);listen(scene,'lostpointercapture',end);
 listen(scene,'click',e=>{const b=e.target.closest('[data-action]');if(!b)return;if(suppressClick){suppressClick=false;return;}request(b.dataset.action);});
 listen(status,'click',()=>{failed=false;render(mode);});listen(win,'resize',()=>layout());listen(win.visualViewport,'resize',()=>layout());listen(win.visualViewport,'scroll',()=>layout());
 const resize=win.ResizeObserver?new win.ResizeObserver(()=>layout()):null;for(const n of [document.querySelector('#chat'),document.querySelector('#send_form')])if(n)resize?.observe(n);
 render();return {setVisible,isVisible:()=>shown,refresh:()=>{if(getMotion())reaction.refresh();else{reaction.dismiss('motion-off');paint();}},setMode:next=>render(next,true),report:()=>({shown,mode,page,ready,failed,position,geometry:g,reaction:reaction.report()}),dispose(){alive=false;epoch++;reaction.dispose();resize?.disconnect();off.splice(0).forEach(f=>f());host.remove();images.clear();imageJobs.clear();}};
}
