// Generated by tools/build-reader.mjs from byte-preserved Foundation r243 sources.
// No eval, host access, storage writes, or dynamic dependency loading.
const foundationModules={
"body-count.cjs":[function(module,exports,require){
'use strict';
const fail=code=>{throw Object.assign(new Error('TISHA_OUTPUT_'+code),{code:'TISHA_OUTPUT_'+code});};
// Deterministic text projection. Does not render HTML, run CSS/JS, or count URLs,
// tag names and attributes. Custom CSS visibility is outside this definition.
const entities={amp:'&',lt:'<',gt:'>',quot:'"',apos:"'",nbsp:' ',ensp:' ',emsp:' ',thinsp:' ',ndash:'–',mdash:'—',hellip:'…',lsquo:'‘',rsquo:'’',ldquo:'“',rdquo:'”',copy:'©',reg:'®',trade:'™',times:'×',divide:'÷',middot:'·'};
function visibleText(text){
 if(typeof text!=='string')fail('BODY_TYPE');
 const code=[];let t=text.replace(/(^|\n)[ \t]*(`{3,}|~{3,})[^\n]*\n([\s\S]*?)\n[ \t]*\2[ \t]*(?=\n|$)/g,(_,lead,fence,body)=>{code.push(body);return lead+'\uE000'+(code.length-1)+'\uE001';})
 .replace(/(`+)([^\n]*?)\1/g,(_,ticks,body)=>{code.push(body);return '\uE000'+(code.length-1)+'\uE001';})
 .replace(/<!--[^]*?-->/g,'').replace(/<(script|style|template|head)\b[^>]*>[^]*?<\/\1\s*>/gi,'')
 .replace(/<([a-z][\w:-]*)\b(?=[^>]*\bhidden(?:\s|=|>))[^>]*>[^]*?<\/\1\s*>/gi,'')
 .replace(/<([a-z][\w:-]*)\b(?=[^>]*\bstyle\s*=\s*["'][^"']*(?:display\s*:\s*none|visibility\s*:\s*hidden))[^>]*>[^]*?<\/\1\s*>/gi,'')
 .replace(/<https?:\/\/([^>]+)>/gi,(_,tail)=>'https://'+tail)
 .replace(/<\/?[a-z][^>]*>/gi,' ').replace(/<![^>]*>/g,'')
 .replace(/^\s{0,3}\[[^\]]+\]:[^\n]*$/gm,'')
 .replace(/!\[(?:\\.|[^\]\\])*\]\([^\n]*?\)/g,'')
 .replace(/!\[[^\]]*\]\[[^\]]*\]/g,'')
 .replace(/\[((?:\\.|[^\]\\])*)\]\((?:\\.|[^()\\]|\([^()]*\))*\)/g,'$1')
 .replace(/\[([^\]]+)\]\[[^\]]*\]/g,'$1')
 .replace(/&(#x[\da-f]+|#\d+|[a-z][\da-z]+);/gi,(match,name)=>{
  if(name[0]==='#'){const n=name[1].toLowerCase()==='x'?parseInt(name.slice(2),16):Number(name.slice(1));return n>0&&n<=0x10ffff&&!(n>=0xd800&&n<=0xdfff)?String.fromCodePoint(n):'�';}
  if(Object.hasOwn(entities,name))return entities[name];fail('ENTITY_UNSUPPORTED');
 }).replace(/\uE000(\d+)\uE001/g,(_,i)=>code[Number(i)]);
 return t.normalize('NFC').replace(/[0-9#*]\ufe0f?\u20e3/g,'');
}
function countBody(text,unit='字'){
 const t=visibleText(require('./numbered-paragraphs.cjs').text(text));
 if(unit==='字')return [...t].filter(c=>/[\p{L}\p{N}]/u.test(c)).length;
 if(unit!=='词')fail('COUNT_UNIT');
 if(typeof Intl?.Segmenter!=='function')fail('WORD_SEGMENTER_UNAVAILABLE');
 return [...new Intl.Segmenter('und',{granularity:'word'}).segment(t)].filter(s=>s.isWordLike).length;
}
const {extractXMLBody:extractBody}=require('./xml-envelope.cjs');
module.exports={visibleText,countBody,extractBody};

},{"./numbered-paragraphs.cjs":"numbered-paragraphs.cjs","./xml-envelope.cjs":"xml-envelope.cjs"}],
"journey-reader.cjs":[function(module,exports,require){
'use strict';

// A reply-local reader view. Never use this result as the live state store, a
// generation input, or an ACL-bearing copy of the memory protocol.
const {parseDisplayEnvelope}=require('./xml-envelope.cjs');
const {parse}=require('./world/strict-json.cjs');
const ACL=require('./permission-wire.cjs');
const memoryPermissions=require('./memory-permissions.cjs');
const {parseStatus}=require('./status-wire.cjs');
const paragraphs=require('./numbered-paragraphs.cjs');
const {visibleText}=require('./body-count.cjs');

const own=(x,k)=>Object.hasOwn(x,k);
const clone=x=>structuredClone(x);
const reader={mode:'emit',audience:'读者'};
const allows=(permission,path)=>ACL.allows(permission,{...reader,path});
const fail=code=>{throw Object.assign(Error('TISYA_JOURNEY_'+code),{code:'TISYA_JOURNEY_'+code});};

function publicPolicy(permission){
  // A native JSON field is atomic. Do not expose private nested members by
  // testing only its default policy or by removing keys from business values.
  return Array.isArray(permission)?allows(permission,''):
    allows(permission.默认,'')&&Object.values(permission.字段).every(p=>allows(p,''));
}

function eventScene(event){
  const a=path=>allows(event.权限,path);
  return {
    title:a('/场景/0/0')?event.标题:null,
    time:a('/场景/0/1')?{start:event.时间.起,end:event.时间.止}:null,
    places:a('/场景/0/2')?clone(event.地点):null,
    world:a('/场景/0/3')?event.世界:null
  };
}

function childAllows(event,label,index,row,column){
  return allows(event.权限,`/${label}/${index}/${column}`)&&allows(row.权限,'/'+column);
}

function publicBodyParagraphs(body){
  // The schema has no no-spoiler/future-plan flag. Psychology is therefore only
  // an optional echo of COMPLETE content + evidence already in this reply's
  // public prose, never a new disclosure or a keyword-based redaction.
  // Arbitrary CSS can hide HTML text. Fail closed on HTML-bearing paragraphs;
  // visibleText also removes Markdown metadata, reference URLs and image alt.
  return paragraphs.read(body,{required:true})
    .filter(p=>!/<(?:\/?[A-Za-z][\w:-]*\b|!--|![A-Za-z])/.test(p.raw))
    .map(p=>visibleText(p.raw));
}

function changeValues(row,oldAllowed){
  const hasOldValue=own(row,'旧值')&&oldAllowed;
  const hasNewValue=own(row,'新值');
  return {
    hasOldValue,...(hasOldValue?{oldValue:clone(row.旧值)}:{}),
    hasNewValue,...(hasNewValue?{newValue:clone(row.新值)}:{}),
    deleted:row.删除===true
  };
}

function statusChanges(status,sidecars){
  const changes=[];
  const nativePolicies=new Map(sidecars.filter(x=>x.区块==='status')
    .map(x=>[JSON.stringify(x.定位),x.权限]));
  for(const [type,objects]of Object.entries(status))for(const [object,fields]of Object.entries(objects)){
    for(const [field,row]of Object.entries(fields)){
      if(type==='叙事状态'){
        // Latest/new value authorization is required. A hidden new value must
        // never make an old value look current, including hidden deletions.
        if(![0,2,4].every(c=>allows(row.权限,'/'+c)))continue;
        changes.push({kind:'status',object,field,...changeValues(row,allows(row.权限,'/3'))});
      }else{
        const permission=nativePolicies.get(JSON.stringify([type,object,field]));
        if(!permission||!publicPolicy(permission))continue;
        changes.push({kind:'status',type,object,field,hasOldValue:false,
          hasNewValue:true,newValue:clone(row),deleted:false});
      }
    }
  }
  return changes;
}

function unique(rows){
  const seen=new Set();
  return rows.filter(row=>{const key=JSON.stringify(row);if(seen.has(key))return false;seen.add(key);return true;});
}

/**
 * Public memory/5 fields from one original reply, with no writes or inference.
 * Unsupported legacy data throws TISYA_JOURNEY_MEMORY_UNSUPPORTED. Callers may
 * keep the original legacy narrative; they must not invent its missing ACLs.
 * playerName is an already-resolved exact name. This module does not bind cards,
 * infer aliases, query history, execute timers, or create task/inventory data.
 */
function projectJourney(source,{showPsychology=false,playerName=null}={}){
  const envelope=parseDisplayEnvelope(source);
  if(!envelope.blocks.memory?.trim())fail('MEMORY_UNSUPPORTED');
  const memory=parse(envelope.blocks.memory);
  if(memory?.protocol!=='tisya.lab.memory/5')fail('MEMORY_UNSUPPORTED');
  memoryPermissions.validate(memory,{body:envelope.blocks.body});
  const status=parseStatus(envelope.blocks.status);
  memoryPermissions.validateLocators(memory,envelope.blocks);

  const associations=memory.关联权限&&allows(memory.关联权限,'/0')?clone(memory.关联):[];
  const changes=[];
  const memories=[];
  const characters=new Map();
  const boundPlayer=typeof playerName==='string'&&playerName?playerName:null;
  const publicProse=showPsychology===true?publicBodyParagraphs(envelope.blocks.body):[];
  const echoed=text=>publicProse.some(p=>p.includes(text));
  const character=name=>{
    if(name===boundPlayer)return null;
    if(!characters.has(name))characters.set(name,{name,cognition:[],psychology:[]});
    return characters.get(name);
  };

  for(const event of memory.事件){
    const a=path=>allows(event.权限,path);
    const scene=eventScene(event);
    const participants=a('/0')?clone(event.参与者):[];
    const summary=a('/2')?event.梗概:null;
    const quote=a('/原文/0/0')&&event.段落!==null?
      {reference:event.段落,text:event.原文}:null;
    const results=event.结果.filter((_,i)=>a(`/结果/${i}/0`));
    const impact=a('/影响/0/0')?event.影响:null;
    const cognition=[];
    const psychology=[];
    const setting=[];

    event.认知.forEach((row,i)=>{
      const allowed=c=>childAllows(event,'认知',i,row,c);
      if(![0,1,4,5].every(allowed))return;
      const value={kind:row.类别,content:row.内容,source:row.来源};
      // '误信' and '确认' reveal a truth assessment. They do not affect whether
      // the independently-authorized understanding itself may be displayed.
      if(allowed(2)&&['听闻','推测'].includes(row.确信))value.certainty=row.确信;
      cognition.push({name:row.主体,value});
    });
    if(showPsychology===true)event.角色心理.forEach((row,i)=>{
      if(![0,2,3].every(c=>childAllows(event,'心理',i,row,c))||
        !echoed(row.内容)||!echoed(row.依据))return;
      psychology.push({name:row.主体,value:{content:row.内容,evidence:row.依据}});
    });
    event.设定变动.forEach((row,i)=>{
      const allowed=c=>childAllows(event,'变动',i,row,c);
      if(![0,1,3].every(allowed))return;
      setting.push({kind:'setting',object:row.对象,field:row.字段,
        ...changeValues(row,allowed(2)),
        ...(a('/变因/0/0')&&event.设定原因!==null?{reason:event.设定原因}:{})});
    });

    const hasCard=summary!==null||quote!==null||results.length>0||impact!==null;
    if(!hasCard&&!cognition.length&&!psychology.length&&!setting.length)continue;
    participants.forEach(character);
    cognition.forEach(({name,value})=>character(name)?.cognition.push(value));
    psychology.forEach(({name,value})=>character(name)?.psychology.push(value));
    changes.push(...setting);
    if(!hasCard)continue; // No title/participant/tag-only or hidden-count shells.

    // No semantic/keyword guess about a free tag. Only already-authorized exact
    // object/person/place/world names can become neutral browse labels.
    const neutralNames=new Set([...associations,...participants,...(scene.places??[]),
      ...(scene.world===null?[]:[scene.world]),...setting.map(x=>x.object)]);
    const tags=a('/标签/0/0')?event.标签.filter(x=>neutralNames.has(x)):[];
    memories.push({scene,participants,summary,quote,results,impact,tags});
  }

  changes.push(...statusChanges(status,memory.权限));
  return {
    scene:memories.length?clone(memories[0].scene):null,
    associations,memories,
    characters:[...characters.values()].map(c=>({...c,
      cognition:unique(c.cognition),psychology:unique(c.psychology)})),
    // Historical setting changes and this reply's status changes are distinct
    // kinds. Deduplication never merges the two or compares hidden fields.
    changes:unique(changes)
  };
}

module.exports={projectJourney};

},{"./xml-envelope.cjs":"xml-envelope.cjs","./world/strict-json.cjs":"world/strict-json.cjs","./permission-wire.cjs":"permission-wire.cjs","./memory-permissions.cjs":"memory-permissions.cjs","./status-wire.cjs":"status-wire.cjs","./numbered-paragraphs.cjs":"numbered-paragraphs.cjs","./body-count.cjs":"body-count.cjs"}],
"json-parser.cjs":[function(module,exports,require){
'use strict';
// JSON.parse无法保留同层重键证据；原文先做完整语法解析并拒绝解码后同名键。
function createStrictJSON({maxDepth=512,nullPrototype=false,onError=null,bareStrings=false}={}){
 return function parse(text){
 if(typeof text!=='string')throw TypeError('JSON原文必须为字符串');let pos=0;
 const error=(message,kind='syntax')=>{if(onError)return onError(kind,pos,message);throw Error('JSON '+pos+': '+message);};
 const ws=()=>{while(/[\x20\t\r\n]/.test(text[pos]??'!'))pos++;};
 function string(){const start=pos++;for(;;){const c=text[pos++];if(c===undefined)error('字符串未闭合');if(c==='\\'){if(pos>=text.length)error('转义未闭合');pos++;continue;}if(c==='"'){try{return JSON.parse(text.slice(start,pos));}catch{error('非法字符串');}}}}
 function key(){if(text[pos]==='"')return string();if(!bareStrings)error('对象键必须是字符串');const start=pos;while(pos<text.length&&!/[:,{}\[\]"\r\n]/.test(text[pos]))pos++;const k=text.slice(start,pos).trim();if(!k)error('对象键不能为空');return k;}
 function value(depth=0){if(depth>maxDepth)error('嵌套过深','depth');ws();const c=text[pos];
  if(c==='"')return string();
  if(c==='{'){pos++;const result=nullPrototype?Object.create(null):{},keys=new Set();ws();if(text[pos]==='}'){pos++;return result;}for(;;){ws();const name=key();if(keys.has(name))error('重复键 '+name,'duplicate');keys.add(name);ws();if(text[pos++]!==':')error('缺少冒号');const v=value(depth+1);Object.defineProperty(result,name,{value:v,writable:true,enumerable:true,configurable:true});ws();const end=text[pos++];if(end==='}')return result;if(end!==',')error('对象缺少逗号或闭括号');}}
  if(c==='['){pos++;const result=[];ws();if(text[pos]===']'){pos++;return result;}for(;;){result.push(value(depth+1));ws();const end=text[pos++];if(end===']')return result;if(end!==',')error('数组缺少逗号或闭括号');}}
  const start=pos;while(pos<text.length&&!(bareStrings?(depth===0?/[\]}]/:/[,\]}]/):/[\x20\t\r\n,\]}]/).test(text[pos]))pos++;const token=text.slice(start,pos).trim();if(!token){if(bareStrings&&depth===0)return '';error('缺少值');}
  if(bareStrings){
   if(token==='null')return null;if(token==='true')return true;if(token==='false')return false;
   if(/^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$/.test(token)){const n=Number(token);if(!Number.isFinite(n))error('非法数值','number');return n;}
   if(token==='~'||/^(?:NaN|[+-]?Infinity)$/.test(token)||/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d*)?$/.test(token))error('非法值 '+token.slice(0,32));
   if(/[\[\]{}\r\n]/.test(token))error('文本或结构未正确分隔');return token;
  }
  let v;try{v=JSON.parse(token);}catch{error('非法值 '+token.slice(0,32));}if(v!==null&&typeof v!=='number'&&typeof v!=='boolean')error('非法值 '+token.slice(0,32));if(typeof v==='number'&&!Number.isFinite(v))error('非法值 '+token.slice(0,32),'number');return v;
 }
 const result=value();ws();if(pos!==text.length)error('多余尾随内容');return result;
}
}
module.exports={createStrictJSON};

},{}],
"memory-permissions.cjs":[function(module,exports,require){
'use strict';
const ACL=require('./permission-wire.cjs');
const bad=c=>{throw Object.assign(Error('TISYA_MEMORY5_'+c),{code:'TISYA_MEMORY5_'+c});};
const object=x=>x!==null&&typeof x==='object'&&!Array.isArray(x);
const exact=(v,keys,optional=[])=>{if(!object(v)||keys.some(k=>!Object.hasOwn(v,k))||Object.keys(v).some(k=>!keys.includes(k)&&!optional.includes(k)))bad('FIELDS');};
const str=(x,nullable=false)=>{if(nullable&&x===null)return;if(typeof x!=='string'||!x.trim()||x.length>24000)bad('TEXT');};
const list=(x,limit=128)=>{if(!Array.isArray(x)||x.length>limit)bad('LIST');};
const strings=x=>{list(x);x.forEach(v=>str(v));if(new Set(x).size!==x.length)bad('DUPLICATE');};
const cellPaths=n=>Array.from({length:n},(_,i)=>'/'+i);
function permission(p,paths){return ACL.validate(p,paths);}
function change(x){exact(x,['对象','字段','权限'],['旧值','新值','删除']);str(x.对象);str(x.字段);if(Object.hasOwn(x,'新值')===Object.hasOwn(x,'删除')||Object.hasOwn(x,'删除')&&x.删除!==true)bad('CHANGE');permission(x.权限,['/0','/1','/2','/3']);}
function eventPaths(e){
 const paths=['/0','/2','/原文/0/0','/场景/0/0','/场景/0/1','/场景/0/2','/场景/0/3','/影响/0/0','/变因/0/0','/标签/0/0'];
 for(const [label,key,columns]of [['结果','结果',[0]],['伏笔','伏笔',[0,1,2,3]],['认知','认知',[0,1,2,4,5]],['心理','角色心理',[0,2,3]],['变动','设定变动',[0,1,2,3]]])e[key].forEach((x,i)=>columns.forEach(j=>paths.push('/'+label+'/'+i+'/'+j)));
 return paths;
}
function validate(q,{body}={}){
 exact(q,['protocol','关联','关联权限','权限','事件','未完事项','倒计时']);if(q.protocol!=='tisya.lab.memory/5')bad('PROTOCOL');strings(q.关联);if(q.关联权限!==null)permission(q.关联权限,['/0']);else if(q.关联.length)bad('ASSOCIATION_PERMISSION');
 list(q.权限,256);const targets=new Set();for(const x of q.权限){exact(x,['区块','定位','权限']);if(!['status','vars','extra'].includes(x.区块))bad('ACL_BLOCK');const k=JSON.stringify([x.区块,x.定位]);if(targets.has(k))bad('ACL_DUPLICATE');targets.add(k);if(x.区块==='vars')ACL.pointer(x.定位);else{list(x.定位);if(x.定位.length!==(x.区块==='status'?3:2))bad('ACL_TARGET');x.定位.forEach(v=>str(v));}permission(x.权限);}
 list(q.事件,64);for(const e of q.事件){
  exact(e,['标题','时间','地点','世界','参与者','权限','梗概','结果','影响','原文','段落','伏笔','认知','角色心理','设定变动','设定原因','标签']);
  str(e.标题,true);exact(e.时间,['起','止']);str(e.时间.起,true);str(e.时间.止,true);if(e.地点!==null)strings(e.地点);str(e.世界,true);strings(e.参与者);str(e.梗概);strings(e.结果);str(e.影响,true);str(e.原文,true);strings(e.标签);
  for(const k of ['伏笔','认知','角色心理','设定变动'])list(e[k]);
  permission(e.权限,eventPaths(e));
  if(e.段落!==null){str(e.段落);if(typeof body==='string'&&require('./numbered-paragraphs.cjs').resolve(e.段落,body)!==e.原文)bad('QUOTE');}else if(e.原文!==null)bad('QUOTE_REFERENCE');
  for(const x of e.伏笔){exact(x,['动作','对象','词','依据']);if(!['埋下','推进','回收'].includes(x.动作))bad('HOOK');strings(x.对象);str(x.词);str(x.依据);}
  for(const x of e.认知){exact(x,['主体','类别','确信','权限','内容','来源']);str(x.主体);str(x.内容);str(x.来源);if(!['自我','对外'].includes(x.类别)||!['确认','听闻','推测','误信'].includes(x.确信))bad('COGNITION');permission(x.权限,['/0','/1','/2','/4','/5']);}
  for(const x of e.角色心理){exact(x,['主体','权限','内容','依据']);str(x.主体);str(x.内容);str(x.依据);permission(x.权限,['/0','/2','/3']);}
  e.设定变动.forEach(change);str(e.设定原因,true);if(e.设定变动.length&&e.设定原因===null)bad('REASON');
 }
 list(q.未完事项,64);for(const x of q.未完事项){exact(x,['状态','事项','对象','触发','依据','权限']);if(!['待处理','完成','取消'].includes(x.状态))bad('TASK');str(x.事项);strings(x.对象);str(x.触发);str(x.依据);permission(x.权限,cellPaths(5));}
 list(q.倒计时,32);for(const x of q.倒计时){exact(x,['计时','延后','对象','地点','内容','权限','条件','失效']);if(!['天','轮'].includes(x.计时)||!Number.isSafeInteger(x.延后)||x.延后<1||x.延后>1000)bad('TIMER');strings(x.对象);str(x.地点,true);str(x.内容);const paths=cellPaths(5);for(const k of ['条件','失效']){list(x[k]);x[k].forEach((c,i)=>{exact(c,['对象','公开字段','等于','权限']);str(c.对象);str(c.公开字段);permission(c.权限,cellPaths(3));cellPaths(3).forEach(p=>paths.push('/'+k+'/'+i+p));});}permission(x.权限,paths);}
 return q;
}
function all(p,paths,opts){return paths.every(path=>ACL.allows(p,{...opts,path}));}
// Filter using the original transport paths. The source remains unchanged.
// A field's name, cause and evidence need the same independent authorization.
function projectEvent(e,opts={}){
 const a=path=>ACL.allows(e.权限,{...opts,path});
 const out={...structuredClone(e),标题:a('/场景/0/0')?e.标题:null,时间:a('/场景/0/1')?e.时间:{起:null,止:null},地点:a('/场景/0/2')?e.地点:null,世界:a('/场景/0/3')?e.世界:null,参与者:a('/0')?e.参与者:[],梗概:a('/2')?e.梗概:null,原文:a('/原文/0/0')?e.原文:null,段落:null,影响:a('/影响/0/0')?e.影响:null,设定原因:a('/变因/0/0')?e.设定原因:null,标签:a('/标签/0/0')?e.标签:[]};
 out.结果=e.结果.filter((x,i)=>a('/结果/'+i+'/0'));
 for(const [label,key,cols,ownCols]of [['伏笔','伏笔',[0,1,2,3]],['认知','认知',[0,1,2,4,5],[0,1,2,4,5]],['心理','角色心理',[0,2,3],[0,2,3]],['变动','设定变动',[0,1,2,3],[0,1,2,3]]])out[key]=e[key].filter((x,i)=>cols.every(c=>a('/'+label+'/'+i+'/'+c))&&(!ownCols||all(x.权限,ownCols.map(c=>'/'+c),opts)));
 if(!out.梗概&&!out.原文&&!out.结果.length&&!out.影响&&!out.伏笔.length&&!out.认知.length&&!out.角色心理.length&&!out.设定变动.length)return null;
 return out;
}
function visibleTask(t,opts={}){return all(t.权限,cellPaths(5),opts);}
function visibleTimer(t,opts={}){return all(t.权限,cellPaths(5),opts)&&['条件','失效'].every(k=>t[k].every((c,i)=>all(c.权限,cellPaths(3),opts)&&all(t.权限,cellPaths(3).map(p=>'/'+k+'/'+i+p),opts)));}
function validateLocators(q,b){
 const parsed={status:JSON.parse(b.status||'{}'),vars:b.vars.trim()?JSON.parse(b.vars):{}};
 for(const x of q.权限){
  const parts=x.区块==='vars'?ACL.pointer(x.定位):x.定位;
  if(x.区块==='extra'){
   let component=false,found=false;const stack=[];for(const t of require('./xml-envelope.cjs').xmlTokens('<reply><extra>'+b.extra+'</extra></reply>')){if(t.kind==='open'){stack.push(t.name);if(t.name===parts[0])component=true;if(component&&t.name===parts[1])found=true;if(t.selfClose)stack.pop();}else if(t.kind==='close'){if(t.name===parts[0])component=false;stack.pop();}}
   if(!found)bad('ACL_EXTRA_TARGET');continue;
  }
  let v=parsed[x.区块];for(const p of parts){if(v===null||typeof v!=='object'||!Object.hasOwn(v,p))bad('ACL_UNRESOLVED');v=v[p];}
 }
 for(const [type,objects]of Object.entries(parsed.status))if(type!=='叙事状态')for(const [name,fields]of Object.entries(objects))for(const field of Object.keys(fields))if(!q.权限.some(x=>x.区块==='status'&&JSON.stringify(x.定位)===JSON.stringify([type,name,field])))bad('STATUS_PERMISSION_MISSING');
 if(parsed.vars.operations?.length&&!q.权限.some(x=>x.区块==='vars'))bad('VARS_PERMISSION_MISSING');
}
module.exports={validate,projectEvent,visibleTask,visibleTimer,validateLocators,eventPaths,all};

},{"./permission-wire.cjs":"permission-wire.cjs","./numbered-paragraphs.cjs":"numbered-paragraphs.cjs","./xml-envelope.cjs":"xml-envelope.cjs"}],
"numbered-paragraphs.cjs":[function(module,exports,require){
'use strict';
// Reply-local paragraph addresses. Original message bytes remain authoritative.
const fail=code=>{throw Object.assign(Error('TISYA_PARAGRAPH_'+code),{code:'TISYA_PARAGRAPH_'+code});};
function read(body,{required=false}={}){
 if(typeof body!=='string')fail('BODY');
 if(!/^\s*1\r?\n/.test(body)){if(required)fail('NUMBERING_REQUIRED');return null;}
 const marks=[];let fence=null,pre=false;
 for(const m of body.matchAll(/[^\r\n]*(?:\r\n|\n|\r|$)/g)){
  if(!m[0])continue;const line=m[0].replace(/[\r\n]+$/,'');
  const fm=/^\s*(`{3,}|~{3,})/.exec(line);
  if(!fence&&!pre&&/^[0-9]+$/.test(line))marks.push({id:Number(line),start:m.index,end:m.index+m[0].length,token:line});
  if(fm){if(fence&&fm[1][0]===fence[0]&&fm[1].length>=fence.length)fence=null;else if(!fence)fence=fm[1];}
  if(/<pre(?:\s|>)/i.test(line))pre=true;if(/<\/pre\s*>/i.test(line))pre=false;
 }
 if(!marks.length||body.slice(0,marks[0].start).trim())fail('PREFIX');
 return marks.map((m,i)=>{
  if(!Number.isSafeInteger(m.id)||m.id!==i+1||m.token!==String(i+1))fail('SEQUENCE');
  let start=m.end,end=marks[i+1]?.start??body.length;const sourceEnd=end;
  // Full blank lines around numbered content are layout padding, not another
  // paragraph. Keep content bytes/offsets intact and still reject interior gaps.
  start+=/^(?:[^\S\r\n]*(?:\r\n|\n|\r))+/.exec(body.slice(start,end))?.[0].length??0;
  end-=/(?:(?:\r\n|\n|\r)[^\S\r\n]*)+$/.exec(body.slice(start,end))?.[0].length??0;
  const raw=body.slice(start,end);if(!raw.trim())fail('EMPTY');
  let code=null,inPre=false;
  for(const line of raw.replace(/\r\n?/g,'\n').split('\n')){
   const fm=/^\s*(`{3,}|~{3,})/.exec(line);
   if(!code&&!inPre&&!line.trim())fail('UNNUMBERED_PARAGRAPH');
   if(fm){if(code&&fm[1][0]===code[0]&&fm[1].length>=code.length)code=null;else if(!code)code=fm[1];}
   if(/<pre(?:\s|>)/i.test(line))inPre=true;if(/<\/pre\s*>/i.test(line))inPre=false;
  }
  // An unfinished protected block owns its trailing whitespace too. Preserve
  // the prior newline-only boundary instead of trimming code/pre content.
  if(code||inPre){end=sourceEnd;while(end>start&&/[\r\n]/.test(body[end-1]))end--;}
  return {id:m.id,raw:body.slice(start,end),start,end};
 });
}
function text(body){const p=read(body);return p?p.map(x=>x.raw).join('\n\n'):body;}
function resolve(reference,body){
 if(!/^段落[1-9]\d*(?:、[1-9]\d*)*$/.test(reference))fail('REFERENCE');
 const p=read(body,{required:true}),ids=reference.slice(2).split('、').map(Number);
 let previous=0;return ids.map(id=>{
  if(!Number.isSafeInteger(id)||id<=previous||id>p.length)fail('REFERENCE_RANGE_OR_ORDER');
  previous=id;return p[id-1].raw;
 }).join('\n\n');
}
module.exports={read,text,resolve};

},{}],
"permission-wire.cjs":[function(module,exports,require){
'use strict';
const fail=c=>{throw Object.assign(Error('TISYA_PERMISSION_'+c),{code:'TISYA_PERMISSION_'+c});};
const object=x=>x!==null&&typeof x==='object'&&!Array.isArray(x);
function tuple(p){
 if(!Array.isArray(p)||p.length!==4||!['A','B','C','D','E',null].includes(p[0]))fail('SHAPE');
 for(const a of p.slice(1))if(a!==null&&(!Array.isArray(a)||a.some(x=>typeof x!=='string'||!x.trim())||new Set(a).size!==a.length))fail('AUDIENCE');
 return p;
}
function pointer(s){if(typeof s!=='string'||!/^\/(?:[^~]|~[01])*$/.test(s))fail('POINTER');return s.split('/').slice(1).map(x=>x.replace(/~1/g,'/').replace(/~0/g,'~'));}
function validate(p,paths){
 if(Array.isArray(p))return tuple(p);
 if(!object(p)||Object.keys(p).sort().join()!=='字段,默认'||!object(p.字段))fail('SHAPE');
 tuple(p.默认);for(const [key,v]of Object.entries(p.字段)){pointer(key);tuple(v);if(paths&&!paths.some(x=>x===key||x.startsWith(key+'/')))fail('UNRESOLVED_TARGET');}
 return p;
}
function at(p,path=''){validate(p);if(Array.isArray(p))return p;let selected=p.默认,length=0;for(const [k,v]of Object.entries(p.字段))if((path===k||path.startsWith(k+'/'))&&k.length>length){selected=v;length=k.length;}return selected;}
function allows(p,{mode='read',audience='叙事组织',path='',subject=false}={}){const t=at(p,path),scope=t[mode==='emit'?2:1];return Array.isArray(scope)&&scope.includes(audience)&&(!subject||Array.isArray(t[3])&&t[3].includes(audience));}
function conjunct(a,b,opts){return allows(a,opts)&&allows(b,opts);}
module.exports={validate,tuple,at,allows,conjunct,pointer};

},{}],
"pipes-wire.cjs":[function(module,exports,require){
'use strict';
const {split:splitRows,AUDIT}=require('./rows-wire.cjs');
const {parse:json}=require('./world/strict-json.cjs');
// Explicit model-wire grammar; persisted JSON and external update interfaces stay strict.
const wireValue=require('./json-parser.cjs').createStrictJSON({bareStrings:true});
const split=(s,sep='|')=>splitRows(s,sep,{bareText:true}).map(x=>x.trim());
const ACL=require('./permission-wire.cjs');
const bad=c=>{throw Object.assign(Error('TISYA_PIPES_'+c),{code:'TISYA_PIPES_'+c});};
const own=(o,k)=>Object.hasOwn(o,k),put=(o,k,v)=>{if(own(o,k))bad('DUPLICATE');Object.defineProperty(o,k,{value:v,writable:true,enumerable:true,configurable:true});};
function text(s){if(s.startsWith('"')){const x=json(s);if(typeof x!=='string')bad('TEXT');return x;}if(!s||s==='~'||s==='[]'||/[\r\n]/.test(s))bad('TEXT');return s;}
function value(s,t){if(t==='s')return text(s);if(t==='e')return s===''?'':text(s);if(t==='?')return s==='~'?null:text(s);if(t==='j')return wireValue(s);if(t==='p')return ACL.validate(wireValue(s));if(t==='i'){if(!/^(?:0|[1-9]\d*)$/.test(s)||!Number.isSafeInteger(+s))bad('INTEGER');return +s;}if(t==='l'||t==='L'){if(s==='[]')return [];if(s==='~'&&t==='L')return null;const a=split(s,'、').map(text);if(new Set(a).size!==a.length)bad('LIST_DUPLICATE');return a;}bad('TYPE');}
function cells(xs,ts){if(xs.length!==ts.length)bad('COLUMNS');return xs.map((s,i)=>value(s,ts[i]));}
// An absent item in these optional collections is distinct from literal quoted text.
const emptyItem=s=>s===''||s==='~'||s==='[]';
function optionalItem(xs){if(xs.length!==1)bad('COLUMNS');return emptyItem(xs[0])?[]:[text(xs[0])];}
// These two observed spellings have explicit meanings in the current M.07 registry.
// Apply only to the certainty cell; never infer or modify a subject's access rights.
function certainty(s){return s==='hearsay'?'听闻':s==='K3'?'确认':s;}
function records(s){return s.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map(line=>{const i=line.indexOf('：');if(i<1)bad('LABEL');return {name:line.slice(0,i).trim(),raw:split(line.slice(i+1))};});}
function heart(b,x){const [status]=cells(x.slice(0,1),'s');if(!['有内容','沉默','关闭'].includes(status))bad('HEART');if(b.heart===null)b.heart={status,items:[]};else if(b.heart.status!==status||status!=='有内容')bad('HEART_DUPLICATE');if(status==='有内容'){const [,type,mood,text]=cells(x,'ss?s');b.heart.items.push({type,mood:x[2]==='null'?null:mood,text});}else if(x.length!==1)bad('COLUMNS');}
function decode(name,source,{body,title}={}){
 const rows=records(source);
 if(name==='title'){if(rows.length!==1||rows[0].name!=='场景')bad('TITLE');const [text,time,places,world]=cells(rows[0].raw,'s?L?');return {text,time,place:places===null?null:places.join('、'),world,places};}
 if(name==='task'||name==='next'||name==='actions'){
  const b=name==='task'?{tasks:[],refs:{style:[],cast:[]},pending:[],characters:[],heart:null,unlocks:[]}:name==='next'?{tasks:[],audit:[],heart:null,delivered:[],candidates:[]}:{actions:[]};
  for(const {name:n,raw:x}of rows){
   if(n==='心声'&&name!=='actions'){heart(b,x);continue;}
   if(name==='task'){
    if(n==='任务'){const [input,plan,stop]=cells(x,'ses');b.tasks.push({input,plan,stop});}
    else if(n==='资料'){if(x.length===1&&emptyItem(x[0]))continue;if(x.length!==2)bad('COLUMNS');const kind=text(x[0]);if(!['文风','人物'].includes(kind))bad('REF');b.refs[kind==='文风'?'style':'cast'].push(...optionalItem(x.slice(1)));}
    else if(n==='待定')b.pending.push(...optionalItem(x));
    else if(n==='人物'){const [status,actor,intent,evidence]=cells(x,'ss?s');b.characters.push({status,actor,intent,evidence});}
    else if(n==='解锁')b.unlocks.push(cells(x,'sss'));
    else bad('TASK_FIELD');
   }else if(name==='next'){
    if(n==='审计'){const [status,kind,evidence]=cells(x,'sss');if(!AUDIT.includes(kind)||b.audit.some(a=>a.kind===kind))bad('AUDIT');b.audit.push({status,kind,evidence});}
    else if(n==='待办'){const [type,trigger,text]=cells(x,'sss');b.tasks.push({type,trigger,text});}
    else if(n==='已交付')b.delivered.push(...optionalItem(x));
    else if(n==='候选')b.candidates.push(...optionalItem(x));
    else bad('NEXT_FIELD');
   }else{if(n!=='行动')bad('ACTIONS_FIELD');const [type,text,source]=cells(x,'sss');b.actions.push({type,text,source});}
  }
  if(name==='task'&&!b.tasks.length)bad('TASK_REQUIRED');
  if(name!=='actions'&&!b.heart)bad('HEART_REQUIRED');
  if(name==='next')b.audit.sort((a,b)=>AUDIT.indexOf(a.kind)-AUDIT.indexOf(b.kind));
  return b;
 }
 if(name==='status'){
  const b={};let current=null;
  for(const {name:n,raw:x}of rows){
   if(n==='原生状态'){const [type,obj,field,v]=cells(x,'sssj');if(type==='叙事状态')bad('RESERVED_TYPE');if(!own(b,type))put(b,type,{});if(!own(b[type],obj))put(b[type],obj,{});put(b[type][obj],field,v);current=null;}
   else if(n==='叙事状态'){if(x.length!==5)bad('COLUMNS');const [obj,permission,field]=cells(x.slice(0,3),'sps');current={权限:permission,知情:[],...(x[3]==='~'?{}:{旧值:wireValue(x[3])}),...(x[4]==='~'?{删除:true}:{新值:wireValue(x[4])})};if(!own(b,'叙事状态'))put(b,'叙事状态',{});if(!own(b.叙事状态,obj))put(b.叙事状态,obj,{});put(b.叙事状态[obj],field,current);}
   else if(n==='知情'){if(!current)bad('KNOWLEDGE_PARENT');const [主体,等级,依据]=cells(x,'sss');if(!['K0','K1','K2','K3'].includes(等级)||current.知情.some(x=>x.主体===主体))bad('KNOWLEDGE');current.知情.push({主体,等级,依据});}
   else bad('STATUS_FIELD');
  }for(const fields of Object.values(b.叙事状态??{}))for(const v of Object.values(fields))require('./status-wire.cjs').validateNarrativeState(v);return b;
 }
 if(name==='memory'){
  const q={protocol:'tisya.lab.memory/5',关联:[],关联权限:null,权限:[],事件:[],未完事项:[],倒计时:[]};let event=null,timer=null,events=false;const seen=new Set();
  for(const {name:n,raw:x}of rows){
   if(['关联','权限','未完','倒计时','条件','失效'].includes(n)){
    if(events)bad('GLOBAL_ORDER');
    if(n==='关联'){if(seen.has(n))bad('DUPLICATE');seen.add(n);[q.关联,q.关联权限]=cells(x,'lp');}
    else if(n==='权限'){const [区块,定位,权限]=cells(x,'sjp');if(!['status','vars','extra'].includes(区块))bad('ACL_LOCATOR');q.权限.push({区块,定位,权限});}
    else if(n==='未完'){const [状态,事项,对象,触发,依据,权限]=cells(x,'sslssp');q.未完事项.push({状态,事项,对象,触发,依据,权限});timer=null;}
    else if(n==='倒计时'){const [计时,延后,对象,地点,内容,权限]=cells(x,'sil?sp');timer={计时,延后,对象,地点,内容,权限,条件:[],失效:[]};q.倒计时.push(timer);}
    else{if(!timer)bad('TIMER_PARENT');const [对象,公开字段,等于,权限]=cells(x,'ssjp');timer[n].push({对象,公开字段,等于,权限});}
    continue;
   }
   if(n==='事件'){events=true;const [参与者,权限,梗概]=cells(x,'lps');event={标题:title.text,时间:{起:title.time,止:null},地点:title.places,世界:title.world,参与者,权限,梗概,结果:[],影响:null,原文:null,段落:null,伏笔:[],认知:[],角色心理:[],设定变动:[],设定原因:null,标签:[]};q.事件.push(event);seen.clear();continue;}
   if(!event)bad('EVENT_PARENT');
   if(['原文','场景','影响','变因','标签'].includes(n)){if(seen.has(n))bad('DUPLICATE');seen.add(n);}
   if(n==='原文'){const [r]=cells(x,'s');event.段落=r;event.原文=require('./numbered-paragraphs.cjs').resolve(r,body);}
   else if(n==='场景'){const [标题,time,地点,世界]=cells(x,'?jL?');if(!Array.isArray(time)||time.length!==2||time.some(t=>t!==null&&typeof t!=='string'))bad('TIME');Object.assign(event,{标题,时间:{起:time[0],止:time[1]},地点,世界});}
   else if(n==='结果')event.结果.push(cells(x,'s')[0]);
   else if(n==='影响')event.影响=cells(x,'s')[0];
   else if(n==='伏笔'){const [动作,对象,词,依据]=cells(x,'slss');event.伏笔.push({动作,对象,词,依据});}
   else if(n==='认知'){const [主体,类别,确信,权限,内容,来源]=cells(x,'sssp ss'.replace(/ /g,''));event.认知.push({主体,类别,确信:certainty(确信),权限,内容,来源});}
   else if(n==='心理'){const [主体,权限,内容,依据]=cells(x,'spss');event.角色心理.push({主体,权限,内容,依据});}
   else if(n==='变动'){if(x.length!==5)bad('COLUMNS');const [对象,字段]=cells(x.slice(0,2),'ss'),权限=value(x[4],'p');event.设定变动.push({对象,字段,权限,...(x[2]==='~'?{}:{旧值:wireValue(x[2])}),...(x[3]==='~'?{删除:true}:{新值:wireValue(x[3])})});}
   else if(n==='变因')event.设定原因=cells(x,'s')[0];
   else if(n==='标签')event.标签=cells(x,'l')[0];
   else bad('MEMORY_FIELD');
  }
  return q;
 }
 bad('BLOCK');
}
function projectEnvelope(e){
 const r={...e,blocks:{...e.blocks},attrs:{...e.attrs},wire:{version:5,order:Object.keys(e.blocks),attrs:JSON.parse(JSON.stringify(e.attrs))}};
 const title=decode('title',e.blocks.title);r.wire.titlePlaces=title.places;const publicTitle={...title};delete publicTitle.places;
 for(const name of ['task','title','next','status','memory','actions']){
  if(e.attrs[name]?.format!=='pipes'&&!(name==='status'||name==='memory')||!['pipes',undefined].includes(e.attrs[name]?.format))bad('FORMAT_'+name);
  const b=name==='title'?publicTitle:decode(name,e.blocks[name],{body:e.blocks.body,title});
  if(name==='task'){r.wire.unlocks=b.unlocks;delete b.unlocks;}
  r.blocks[name]=JSON.stringify(b);r.attrs[name]={...e.attrs[name],format:'json'};
 }
 require('./numbered-paragraphs.cjs').read(e.blocks.body,{required:true});
 return require('./task-handoff-wire.cjs').toInternal(r);
}
module.exports={decode,projectEnvelope,records,value};

},{"./rows-wire.cjs":"rows-wire.cjs","./world/strict-json.cjs":"world/strict-json.cjs","./json-parser.cjs":"json-parser.cjs","./permission-wire.cjs":"permission-wire.cjs","./status-wire.cjs":"status-wire.cjs","./numbered-paragraphs.cjs":"numbered-paragraphs.cjs","./task-handoff-wire.cjs":"task-handoff-wire.cjs"}],
"rows-wire.cjs":[function(module,exports,require){
'use strict';
// Versioned model transport to the existing JSON contracts. Pure parsing; no writes or evaluation.
const {parse:parseJSON}=require('./world/strict-json.cjs');
const copy=x=>structuredClone(x), same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
const fail=(code,detail)=>{throw Object.assign(Error('ROWS_'+code),{code:'ROWS_'+code,detail});};
const AUDIT=['身份与授权','资料与知情','人物与关系','行动与因果','数值与机制','文风与表现','成稿与交付'];
const esc=x=>x.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
function split(s,sep='|',{bareText=false}={}){
 let a=[],start=0,q=false,e=false,stack=[],atomStart=true;
 for(let i=0;i<s.length;i++){const c=s[i];if(q){if(e)e=false;else if(c==='\\')e=true;else if(c==='"')q=false;continue;}
  if(c==='"'&&(!bareText||atomStart)){q=true;atomStart=false;continue;}
  if((c==='['||c==='{')&&(!bareText||atomStart)){stack.push(c);atomStart=true;continue;}else if((c===']'||c==='}')&&(!bareText||stack.length)){if(stack.pop()!==(c===']'?'[':'{'))fail('BRACKET');atomStart=false;}
  if(c===sep&&!stack.length){a.push(s.slice(start,i));start=i+1;atomStart=true;}
  else if(stack.length&&(c===','||c===':'))atomStart=true;else if(!/\s/.test(c))atomStart=false;
 }if(q||stack.length)fail('UNCLOSED');a.push(s.slice(start));return a;
}
function atom(x){if(typeof x!=='string')fail('STRING');return !x||x==='~'||x==='null'||x.trim()!==x||/[|、\r\n\t"\\\[\]{}<>]/.test(x)||/^[->]/.test(x)||/[·:]$/.test(x)?JSON.stringify(x):x;}
function unatom(s){if(s.startsWith('"')){let v;try{v=JSON.parse(s);}catch(_){fail('QUOTE');}if(typeof v!=='string')fail('STRING');return v;}if(!s||s.trim()!==s||/["\r\n]/.test(s))fail('STRING');return s;}
function cell(v,t){if(t==='l')return v.length?v.map(atom).join('、'):'~';if(t==='j')return JSON.stringify(v);if(t==='a')return v.length?JSON.stringify(v):'~';if(t==='i'){if(!Number.isSafeInteger(v))fail('INTEGER');return String(v);}if(t==='?'&&v===null)return '~';return atom(v);}
function value(s,t){if(t==='l')return s==='~'?[]:split(s,'、').map(unatom);if(t==='j'||t==='a'){if(t==='a'&&s==='~')return [];try{const v=parseJSON(s);if(t==='a'&&!Array.isArray(v))fail('ARRAY');return v;}catch(e){fail('JSON');}}if(t==='i'){if(!/^-?(0|[1-9]\d*)$/.test(s)||!Number.isSafeInteger(+s))fail('INTEGER');return +s;}if(t==='?'&&(s==='~'||s==='null'))return null;return unatom(s);}
const pack=(xs,ts)=>{if(xs.length!==ts.length)fail('COLUMNS');return xs.map((x,i)=>cell(x,ts[i])).join('|');};
const unpack=(s,ts)=>{const xs=split(s);if(xs.length!==ts.length)fail('COLUMNS',{actual:xs.length,expected:ts.length});return xs.map((x,i)=>value(x,ts[i]));};
const R=(s,g,v,gt='',vt='')=>({s,g,v,gt,vt});
function bucket(xs,key){const groups=new Map();for(const x of xs){const k=JSON.stringify(key(x));if(!groups.has(k))groups.set(k,[]);groups.get(k).push(x);}return [...groups.values()].flat();}
function canonical(input){const b=copy(input);
 b.task.characters=bucket(b.task.characters,x=>x.status);
 b.next.tasks=bucket(b.next.tasks,x=>x.type);b.next.actions=bucket(b.next.actions,x=>x.type);
 for(const e of b.memory.事件){
  const byHook=new Map();let ordered=false;for(const h of e.伏笔){const k=JSON.stringify([h.对象,h.词]);if(byHook.has(k)&&byHook.get(k)!==h.动作)ordered=true;byHook.set(k,h.动作);}
  if(!ordered)e.伏笔=bucket(e.伏笔,x=>x.动作);
  e.认知=bucket(e.认知,x=>[x.主体,x.类别,x.确信,x.公开范围,x.知情者]);
  e.角色心理=bucket(e.角色心理,x=>[x.主体,x.公开范围,x.知情者]);
 }
 b.memory.未完事项=bucket(b.memory.未完事项,x=>x.状态);
 b.memory.倒计时=bucket(b.memory.倒计时,x=>x.计时);
 return b;
}
function paragraphSpans(s){
 // Preserve original offsets; paragraph delimiters inside code are not layout.
 if(/^\s*<p(?:\s|>)/i.test(s)){
  const parts=[...s.matchAll(/<p(?:\s[^>]*)?>[\s\S]*?<\/p\s*>/gi)];
  let at=0,only=true;for(const m of parts){if(s.slice(at,m.index).trim())only=false;at=m.index+m[0].length;}if(s.slice(at).trim())only=false;
  if(only&&parts.length)return parts.map(m=>({raw:m[0],start:m.index,end:m.index+m[0].length}));
 }
 const out=[];let start=0,fence=null,pre=false;const add=(a,b)=>{while(b>a&&/[\r\n]/.test(s[b-1]))b--;if(s.slice(a,b).trim())out.push({raw:s.slice(a,b),start:a,end:b});};
 for(const m of s.matchAll(/[^\r\n]*(?:\r\n|\n|\r|$)/g)){
  if(!m[0])continue;const line=m[0].replace(/[\r\n]+$/,'');
  const mark=/^\s*(`{3,}|~{3,})/.exec(line);
  if(mark){if(fence&&mark[1][0]===fence[0]&&mark[1].length>=fence.length)fence=null;else if(!fence)fence=mark[1];}
  if(/<pre(?:\s|>)/i.test(line))pre=true;
  if(!fence&&!pre&&!line.trim()){
   add(start,m.index);start=m.index+m[0].length;
  }
  if(/<\/pre\s*>/i.test(line))pre=false;
 }
 add(start,s.length);return out;
}
function normalizeParagraph(s){
 s=s.replace(/\r\n?/g,'\n').replace(/^\n+|\n+$/g,'');
 if(/```|~~~|<pre\b|<code\b/i.test(s))return s;
 s=s.replace(/<\/?(?:p|em|strong|b|i|span|u|s|small|mark)(?:\s[^>]*)?>/gi,'');
 s=s.replace(/&(amp|lt|gt|quot|apos|#\d+|#x[\da-fA-F]+);/g,(_,x)=>({amp:'&',lt:'<',gt:'>',quot:'"',apos:"'"}[x]??String.fromCodePoint(x[1]==='x'?parseInt(x.slice(2),16):+x.slice(1))));
 const lines=s.split('\n').map(x=>x.trim());while(lines.length&&!lines[0])lines.shift();while(lines.length&&!lines.at(-1))lines.pop();
 return lines.reduce((a,b)=>!a?b:a+(/[\p{Script=Han}]/u.test(a.at(-1))||/[\p{Script=Han}]/u.test(b[0])?'':' ')+b,'');
}
function paragraphs(s){return paragraphSpans(s).map(x=>normalizeParagraph(x.raw));}
function restoreQuote(quote,body){
 const qs=paragraphs(quote),ps=paragraphSpans(body);if(!qs.length)fail('QUOTE_EMPTY');const matches=[];
 for(let i=0;i+qs.length<=ps.length;i++)if(qs.every((q,j)=>normalizeParagraph(ps[i+j].raw)===q))matches.push(body.slice(ps[i].start,ps[i+qs.length-1].end));
 if(!matches.length)fail('QUOTE_NOT_CONTIGUOUS');if(new Set(matches).size>1)fail('QUOTE_AMBIGUOUS');return matches[0];
}
function heart(h){return h.items.length?h.items.map(x=>R('心声',[h.status],[x.type,x.mood,x.text],'s','s?s')):[R('心声',[h.status],[],'s','')];}
function records(name,b){const out=[],push=r=>out.push(r),lines=(s,xs)=>xs.forEach(x=>push(R(s,[],[x],'','s')));
 if(name==='title')return [R('',[],[b.text,b.time,b.place,b.world],'','s???')];
 if(name==='task'){
  b.tasks.forEach(x=>push(R('任务',[],[x.input,x.plan,x.stop],'','sss')));
  for(const [k,label]of [['style','文风'],['cast','人物']])b.refs[k].forEach(x=>push(R('资料',[label],[x],'s','s')));
  lines('待定',b.pending);out.push(...heart(b.heart));
  bucket(b.audit,x=>x.status).forEach(x=>push(R('审计',[x.status],[x.kind,x.evidence],'s','ss')));
  b.characters.forEach(x=>push(R('人物',[x.status],[x.actor,x.intent,x.evidence],'s','s?s')));
 }else if(name==='next'){
  b.tasks.forEach(x=>push(R('待办',[x.type],[x.trigger,x.text],'s','ss')));
  b.actions.forEach(x=>push(R('行动',[x.type],[x.text,x.source],'s','ss')));
  out.push(...heart(b.heart));lines('已交付',b.delivered);lines('候选',b.candidates);
 }else if(name==='status'){
  for(const [type,objs]of Object.entries(b))for(const [obj,fields]of Object.entries(objs))for(const [k,v]of Object.entries(fields))push(R(type,[obj],[k,v],'s','sj'));
 }else if(name==='vars'){
  if(b===null)return [];
  for(const x of b.operations){const pair=['copy','move'].includes(x.op),remove=x.op==='remove';push(R('',[x.op],pair?[x.from,x.path]:remove?[x.path]:[x.path,x.value],'s',pair?'ss':remove?'s':'sj'));}
 }else if(name==='memory'){
  if(b.关联.length)push(R('关联',[],[b.关联],'','l'));
  for(const e of b.事件){
   push(R('事件',[],[e.参与者,e.公开范围,e.知情者,e.梗概],'','lsls'));
   const d=e.场景.差异;for(const k of ['标题','时间','地点','世界'])if(Object.hasOwn(d,k))push(R('场景',[],k==='时间'?[k,d[k].起,d[k].止]:[k,d[k]],'',k==='时间'?'s??':k==='地点'?'sl':'s?'));
   lines('结果',e.结果);if(e.影响!==null)push(R('影响',[],[e.影响],'','s'));
   if(e.原文!==null)for(const p of paragraphs(e.原文))push(R('原文',[],[p],'','s'));
   const seen=new Map();let ordered=false;for(const x of e.伏笔){const k=JSON.stringify([x.对象,x.词]);if(seen.has(k)&&seen.get(k)!==x.动作)ordered=true;seen.set(k,x.动作);}
   for(const x of e.伏笔)push(ordered?R('伏笔序',[],[x.动作,x.对象,x.词,x.依据],'','slss'):R('伏笔',[x.动作],[x.对象,x.词,x.依据],'s','lss'));
   for(const x of e.认知)push(R('认知',[x.主体,x.类别,x.确信,x.公开范围,x.知情者],[x.内容,x.来源],'ssssl','ss'));
   for(const x of e.角色心理)push(R('心理',[x.主体,x.公开范围,x.知情者],[x.内容,x.依据],'ssl','ss'));
   for(const x of e.设定变动)push(R('变动',[x.对象],[x.字段,x.旧值,x.新值],'s','sjj'));
   if(e.设定原因!==null)push(R('变因',[],[e.设定原因],'','s'));
   if(e.标签.length)push(R('标签',[],[e.标签],'','l'));
  }
  for(const x of b.未完事项)push(R('未完',[x.状态],[x.事项,x.对象,x.触发,x.依据],'s','slss'));
  for(const x of b.倒计时)push(R('倒计时',[x.计时],[x.延后,x.对象,x.地点,x.内容,x.条件,x.失效],'s','il?saa'));
 }else fail('BLOCK',name);
 return out;
}
const forms={
 task:{任务:['','sss'],资料:['s','s'],待定:['','s'],心声:['s','s?s'],审计:['s','ss'],人物:['s','s?s']},
 next:{待办:['s','ss'],行动:['s','ss'],心声:['s','s?s'],已交付:['','s'],候选:['','s']},
 memory:{关联:['','l'],事件:['','lsls'],场景:['','*'],结果:['','s'],影响:['','s'],原文:['','s'],伏笔:['s','lss'],伏笔序:['','slss'],认知:['ssssl','ss'],心理:['ssl','ss'],变动:['s','sjj'],变因:['','s'],标签:['','l'],未完:['s','slss'],倒计时:['s','il?saa']}
};
function encodeBlock(name,b,{grouped=true}={}){
 const rs=records(name,b),out=[];let section=null,group=null;
 for(const r of rs){
  if(!grouped){out.push(pack([...(r.s?[r.s]:[]),...r.g,...r.v],(r.s?'s':'')+r.gt+r.vt));continue;}
  if(name==='title'){out.push(pack(r.v,r.vt));continue;}
  if(r.s!==section||r.s==='事件'){if(r.s)out.push(atom(r.s)+':');section=r.s;group=null;}
  if(r.g.length&&!same(group,r.g)){out.push('- '+pack(r.g,r.gt));group=r.g;}
  if(r.s==='原文'){out.push('>'+atom(r.v[0]));continue;}
  if(r.v.length)out.push(pack(r.v,r.vt));
 }return out.join('\n');
}
function parseRecords(name,text){
 if(name==='title'){const xs=text.trim().split('\n');if(xs.length!==1)fail('TITLE');return [R('',[],unpack(xs[0],'s???'))];}
 const out=[];let s=name==='vars'?'':null,g=null,gt='',vt='',pendingHeader=false,header=0;
 for(const [index,line]of text.split(/\r?\n/).entries()){
  if(!line)continue;if(/^\s/.test(line))fail('INDENT',{line:index+1});
  if(line.startsWith('>')){if(s!=='原文')fail('PARAGRAPH');out.push(R(s,[],[unatom(line.slice(1))]));pendingHeader=false;continue;}
  if(/[·:]$/.test(line)){header++;if(pendingHeader)fail('EMPTY_GROUP');s=unatom(line.slice(0,-1));g=null;
   if(name==='status'){gt='s';vt='sj';}else if(!forms[name]?.[s])fail('SECTION',s);else [gt,vt]=forms[name][s];pendingHeader=true;continue;}
  if(line.startsWith('-')){if(s===null)fail('PARENT');if(pendingHeader&&g!==null)fail('EMPTY_GROUP');if(name==='vars'){gt='s';vt='*';}if(!gt)fail('GROUP');g=unpack(line.slice(1).replace(/^ /,''),gt);pendingHeader=true;
   if(s==='心声'&&['沉默','关闭'].includes(g[0])){out.push(R(s,g,[]));pendingHeader=false;}continue;}
  if(s===null||gt&&!g)fail('PARENT');let types=vt;
  if(vt==='*'){if(name==='vars')types=['copy','move'].includes(g[0])?'ss':g[0]==='remove'?'s':'sj';else{const key=unatom(split(line)[0]);types=key==='时间'?'s??':key==='地点'?'sl':key==='标题'||key==='世界'?'s?':fail('SCENE_KEY');}}
  out.push({...R(s,g||[],unpack(line,types)),header});pendingHeader=false;
 }if(pendingHeader)fail('EMPTY_GROUP');return out;
}
function assign(obj,key,v){if(Object.hasOwn(obj,key))fail('DUPLICATE',key);Object.defineProperty(obj,key,{value:v,enumerable:true,writable:true,configurable:true});}
function decodeBlock(name,text){const rs=parseRecords(name,text);
 if(name==='title'){const [text,time,place,world]=rs[0].v;return {text,time,place,world};}
 if(name==='status'){const b={};for(const {s,g,v}of rs){if(!Object.hasOwn(b,s))assign(b,s,{});if(!Object.hasOwn(b[s],g[0]))assign(b[s],g[0],{});assign(b[s][g[0]],v[0],v[1]);}return b;}
 if(name==='vars')return {protocol:'mvu-json-patch',operations:rs.map(({g,v})=>{const op=g[0];if(!['add','replace','remove','delta','test','copy','move','insert'].includes(op))fail('OP');return ['copy','move'].includes(op)?{op,from:v[0],path:v[1]}:op==='remove'?{op,path:v[0]}:{op,path:v[0],value:v[1]};})};
 const b=name==='task'?{tasks:[],refs:{style:[],cast:[]},pending:[],heart:null,audit:[],characters:[]}:name==='next'?{tasks:[],actions:[],heart:null,delivered:[],candidates:[]}:{关联:[],事件:[],未完事项:[],倒计时:[]};
 let e=null,seen=new Set(),rootSeen=new Set(),scalarHeaders={};const once=k=>{if(seen.has(k))fail('DUPLICATE',k);seen.add(k);};
 for(const {s,g,v,header}of rs){
  if(s==='心声'){if(b.heart===null)b.heart={status:g[0],items:[]};else if(b.heart.status!==g[0]||!v.length)fail('HEART');if(v.length){const [type,mood,text]=v;b.heart.items.push({type,mood,text});}continue;}
  if(name==='task'){
   if(s==='任务'){const [input,plan,stop]=v;b.tasks.push({input,plan,stop});}
   if(s==='资料'){const k=g[0]==='文风'?'style':g[0]==='人物'?'cast':fail('REF');b.refs[k].push(v[0]);}
   if(s==='待定')b.pending.push(v[0]);
   if(s==='审计'){const [kind,evidence]=v;b.audit.push({kind,status:g[0],evidence});}
   if(s==='人物'){const [actor,intent,evidence]=v;b.characters.push({actor,intent,status:g[0],evidence});}
  }else if(name==='next'){
   if(s==='待办'){const [trigger,text]=v;b.tasks.push({type:g[0],trigger,text});}
   if(s==='行动'){const [text,source]=v;b.actions.push({type:g[0],text,source});}
   if(s==='已交付')b.delivered.push(v[0]);if(s==='候选')b.candidates.push(v[0]);
  }else{
   if(s==='关联'){if(rootSeen.has(s))fail('DUPLICATE');rootSeen.add(s);b.关联=v[0];continue;}
   if(s==='未完'){const [事项,对象,触发,依据]=v;b.未完事项.push({事项,对象,触发,依据,状态:g[0]});e=null;continue;}
   if(s==='倒计时'){const [延后,对象,地点,内容,条件,失效]=v;b.倒计时.push({计时:g[0],延后,对象,地点,内容,条件,失效});e=null;continue;}
   if(s==='事件'){const [参与者,公开范围,知情者,梗概]=v;e={场景:{引用:'title',差异:{}},参与者,梗概,结果:[],影响:null,原文:null,伏笔:[],认知:[],角色心理:[],公开范围,知情者,设定变动:[],设定原因:null,标签:[]};b.事件.push(e);seen=new Set();scalarHeaders={};continue;}
   if(!e)fail('EVENT_PARENT');
   if(s==='场景')assign(e.场景.差异,v[0],v[0]==='时间'?{起:v[1],止:v[2]}:v[1]);
   if(s==='结果')e.结果.push(v[0]);if(s==='影响'){if(Object.hasOwn(scalarHeaders,s)&&scalarHeaders[s]!==header)fail('DUPLICATE',s);scalarHeaders[s]=header;e.影响=e.影响===null?v[0]:e.影响+'\n'+v[0];}
   if(s==='原文')e.原文=e.原文===null?v[0]:e.原文+'\n\n'+v[0];
   if(s==='伏笔'){const [对象,词,依据]=v;e.伏笔.push({动作:g[0],对象,词,依据});}
   if(s==='伏笔序'){const [动作,对象,词,依据]=v;e.伏笔.push({动作,对象,词,依据});}
   if(s==='认知'){const [主体,类别,确信,公开范围,知情者]=g,[内容,来源]=v;e.认知.push({主体,类别,确信,公开范围,知情者,内容,来源});}
   if(s==='心理'){const [主体,公开范围,知情者]=g,[内容,依据]=v;e.角色心理.push({主体,公开范围,知情者,内容,依据});}
   if(s==='变动'){const [字段,旧值,新值]=v;e.设定变动.push({对象:g[0],字段,旧值,新值});}
   if(s==='变因'){if(Object.hasOwn(scalarHeaders,s)&&scalarHeaders[s]!==header)fail('DUPLICATE',s);scalarHeaders[s]=header;e.设定原因=e.设定原因===null?v[0]:e.设定原因+'\n'+v[0];}if(s==='标签'){once(s);e.标签=v[0];}
  }
 }
 if(name==='task'){if(!b.heart)fail('HEART_REQUIRED');b.audit.sort((a,b)=>AUDIT.indexOf(a.kind)-AUDIT.indexOf(b.kind));}
 if(name==='next'&&!b.heart)fail('HEART_REQUIRED');return b;
}
const NAMES=['task','title','body','status','extra','vars','archive','memory','next'];
function envelope(b,{grouped=true}={}){return '<reply>\n'+NAMES.map(n=>{
 if(n==='archive'||n==='vars'&&b.vars===null)return '<'+n+'/>';
 if(n==='body')return '<body min="2000" max="5000" unit="字">'+b.body+'</body>';
 if(n==='extra')return '<extra>'+b.extra+'</extra>';
 const attrs=n==='task'?' audit_count="7"':n==='next'?' actions_min="4" actions_max="6"':'';
 return '<'+n+' format="rows"'+attrs+'>\n'+esc(encodeBlock(n,b[n],{grouped}))+'\n</'+n+'>';
 }).join('\n')+'\n</reply>';}
// Reuse the production envelope scanner: do not find/replace blocks in body or extra.
function projectEnvelope(e){const r={...e,blocks:{...e.blocks},attrs:{...e.attrs}};
 for(const n of ['task','title','status','vars','memory','next'])if(e.attrs[n]?.format==='rows'){const v=decodeBlock(n,e.blocks[n]);if(n==='memory')for(const x of v.事件)if(x.原文!==null)x.原文=restoreQuote(x.原文,e.blocks.body);r.blocks[n]=JSON.stringify(v);r.attrs[n]={...e.attrs[n],format:'json'};}
 return r;
}
module.exports={canonical,records,encodeBlock,decodeBlock,envelope,projectEnvelope,paragraphs,restoreQuote,split,AUDIT,NAMES};

},{"./world/strict-json.cjs":"world/strict-json.cjs"}],
"status-wire.cjs":[function(module,exports,require){
'use strict';
const {parse}=require('./world/strict-json.cjs');
const object=x=>x!==null&&typeof x==='object'&&!Array.isArray(x);
function parseStatus(text){
 const fail=()=>{throw Object.assign(Error('TISYA_WORLD_STATUS_SHAPE'),{code:'TISYA_WORLD_STATUS_SHAPE'});};
 if(typeof text!=='string'||text.length>64000)fail();
 // Empty legacy blocks remain readable; new output always uses {}.
 const value=text.trim()?parse(text):{};
 if(!object(value))fail();let count=0;
 for(const [type,objects]of Object.entries(value)){
  if(type==='叙事状态'){if(!object(objects))fail();for(const fields of Object.values(objects)){if(!object(fields))fail();for(const v of Object.values(fields)){if(++count>256)fail();validateNarrativeState(v);}}continue;}
  if(!type||!object(objects)||!Object.keys(objects).length)fail();
  for(const [name,fields]of Object.entries(objects)){
   if(!name||!object(fields)||!Object.keys(fields).length)fail();
   for(const [field]of Object.entries(fields))if(!field||++count>256)fail();
  }
 }
 return value;
}
function validateNarrativeState(v){
 const bad=()=>{throw Object.assign(Error('TISYA_NARRATIVE_STATUS_SHAPE'),{code:'TISYA_NARRATIVE_STATUS_SHAPE'});};
 if(!object(v)||!Object.hasOwn(v,'权限')||!Array.isArray(v.知情)||Object.keys(v).some(k=>!['权限','知情','旧值','新值','删除'].includes(k))||Object.hasOwn(v,'新值')===Object.hasOwn(v,'删除')||Object.hasOwn(v,'删除')&&v.删除!==true)bad();
 require('./permission-wire.cjs').validate(v.权限,['/0','/2','/3','/4',...v.知情.flatMap((x,i)=>[0,1,2].map(c=>'/知情/'+i+'/'+c))]);const used=new Set();
 for(const x of v.知情){if(!object(x)||Object.keys(x).sort().join()!=='主体,依据,等级'||typeof x.主体!=='string'||!x.主体.trim()||used.has(x.主体)||!['K0','K1','K2','K3'].includes(x.等级)||typeof x.依据!=='string'||!x.依据.trim())bad();used.add(x.主体);}return v;
}
function nativeStatus(v){return Object.fromEntries(Object.entries(v).filter(([k])=>k!=='叙事状态'));}
module.exports={parseStatus,validateNarrativeState,nativeStatus};

},{"./world/strict-json.cjs":"world/strict-json.cjs","./permission-wire.cjs":"permission-wire.cjs"}],
"strict-json.cjs":[function(module,exports,require){
'use strict';
const {createStrictJSON}=require('./json-parser.cjs');
const suffix={depth:'JSON_DEPTH',duplicate:'DUPLICATE_KEY',number:'JSON_NUMBER',syntax:'JSON_SYNTAX'};
const strictJSON=createStrictJSON({maxDepth:64,nullPrototype:true,onError(kind){const code='TISHA_JSON_'+suffix[kind];throw Object.assign(new Error(code),{code});}});
module.exports={strictJSON};

},{"./json-parser.cjs":"json-parser.cjs"}],
"task-handoff-wire.cjs":[function(module,exports,require){
"use strict";
// Ten-block model wire; adapt once to the existing stored-data schema.
// This is a compatibility view, not a second editable task/audit source.
const bad=c=>{throw Object.assign(Error('TISYA_HANDOFF_'+c),{code:'TISYA_HANDOFF_'+c});};
function toInternal(e){
 const read=n=>{try{return require('./strict-json.cjs').strictJSON(e.blocks[n]);}catch(_){bad('JSON_'+n);}};
 const task=read('task'),next=read('next'),actions=read('actions');
 if((task.audit!==undefined&&(!Array.isArray(task.audit)||task.audit.length))||(next.actions!==undefined&&(!Array.isArray(next.actions)||next.actions.length))||!Array.isArray(next.audit)||!Array.isArray(actions.actions)||Object.keys(actions).join()!=='actions')bad('OWNERSHIP');
 const shape=(name,keys)=>{const a=e.attrs[name];if(!a||Object.keys(a).length!==keys.length||keys.some(k=>!Object.hasOwn(a,k)))bad('ATTR_'+name);};
 shape('task',['format']);shape('next',['format','audit_count']);shape('actions',['format','actions_min','actions_max']);
 if(e.attrs.task.format!=='json'||e.attrs.next.format!=='json'||e.attrs.actions.format!=='json'||e.attrs.next.audit_count!=='7')bad('ATTR_VALUE');
 task.audit=next.audit;delete next.audit;next.actions=actions.actions;
 e.blocks.task=JSON.stringify(task);e.blocks.next=JSON.stringify(next);delete e.blocks.actions;
 e.attrs.task={format:'json',audit_count:'7'};e.attrs.next={format:'json',actions_min:e.attrs.actions.actions_min,actions_max:e.attrs.actions.actions_max};delete e.attrs.actions;
 return e;
}
module.exports={toInternal};

},{"./strict-json.cjs":"strict-json.cjs"}],
"world/strict-json.cjs":[function(module,exports,require){
'use strict';
const {createStrictJSON}=require('../json-parser.cjs');
module.exports={parse:createStrictJSON({maxDepth:512})};

},{"../json-parser.cjs":"json-parser.cjs"}],
"xml-envelope.cjs":[function(module,exports,require){
'use strict';
const LEGACY_NAMES=Object.freeze(['task','title','body','status','extra','vars','archive','memory','next']);
const XML_NAMES=Object.freeze(['task','title','body','next','status','extra','vars','archive','memory','actions']);
const bad=code=>{throw Object.assign(new Error('TISHA_OUTPUT_'+code),{code:'TISHA_OUTPUT_'+code});};
function escapeBareAmpersands(s){
 return s.replace(/&(?!amp;|lt;|gt;|quot;|apos;|#\d+;|#x[\da-fA-F]+;)/g,(m,p)=>{
  if(/^&(?:[A-Za-z_][\w.:-]*|#[^\s&<>;]*);/.test(s.slice(p)))bad('XML_ENTITY');
  return '&amp;';
 });
}
function unxml(s){
 if(/&(?!amp;|lt;|gt;|quot;|apos;|#\d+;|#x[\da-fA-F]+;)/.test(s))bad('XML_ENTITY');
 return s.replace(/&([^;]+);/g,(_,x)=>{const v={amp:'&',lt:'<',gt:'>',quot:'"',apos:"'"}[x];if(v)return v;const n=x[1]==='x'?parseInt(x.slice(2),16):Number(x.slice(1));if(!(n===9||n===10||n===13||n>=32&&n<=0x10ffff&&!(n>=0xd800&&n<=0xdfff)))bad('XML_ENTITY');return String.fromCodePoint(n);});
}
// A complete JSON payload is text inside these envelope blocks. In particular,
// tag names mentioned inside JSON strings do not open XML elements. Recognize
// only a syntactically complete prefix; damaged JSON still reaches the normal
// boundary/strict-JSON checks, including actual nested-reply diagnostics.
const JSON_BLOCKS=new Set(['task','title','status','vars','memory','next','actions']);
function jsonTextEnd(s,start,literalAmpersands){
 let p=start;while(/[\t\n\r ]/.test(s[p]||'')&&p<s.length)p++;
 if(s[p]!=='{'&&s[p]!=='[')return null;
 const stack=[];let quoted=false,escaped=false;
 for(let i=p;i<s.length;){
  let c=s[i++];
  if(c==='&'){
   const entity=/^&(?:amp|lt|gt|quot|apos|#\d+|#x[\da-fA-F]+);/.exec(s.slice(i-1));
   if(entity){c=unxml(entity[0]);i+=entity[0].length-1;}
  }
  if(quoted){if(escaped)escaped=false;else if(c==='\\')escaped=true;else if(c==='"')quoted=false;continue;}
  if(c==='"'){quoted=true;continue;}
  if(c==='<')return null;
  if(c==='{'||c==='[')stack.push(c);
  else if(c==='}'||c===']'){
   if(stack.pop()!==(c==='}'?'{':'['))return null;
   if(!stack.length){
    const raw=s.slice(start,i),value=unxml(literalAmpersands?escapeBareAmpersands(raw):raw);
    try{JSON.parse(value);}catch(_){return null;}
    return i;
   }
  }
 }
 return null;
}
function* xmlTokens(s,{tolerateTail=false,literalAmpersands=false}={}){
 if(typeof s!=='string'||s.length>2000000)bad('SIZE');
 if(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/.test(s))bad('XML_CHARACTER');
 let p=0;const path=[];
 while(p<s.length){
  if(path.length===2&&path[0]==='reply'&&JSON_BLOCKS.has(path[1])){
   const end=jsonTextEnd(s,p,literalAmpersands);
   if(end!==null){const raw=s.slice(p,end);yield {kind:'text',value:unxml(literalAmpersands?escapeBareAmpersands(raw):raw),raw,json:true,start:p,end};p=end;continue;}
  }
  if(s[p]!=='<'){let q=s.indexOf('<',p);if(q<0)q=s.length;const raw=s.slice(p,q);yield {kind:'text',value:unxml(literalAmpersands?escapeBareAmpersands(raw):raw),raw,start:p,end:q};p=q;continue;}
  if(s.startsWith('<![CDATA[',p)){const q=s.indexOf(']]>',p+9);if(q<0){if(tolerateTail)return;bad('XML_CDATA');}yield {kind:'text',value:s.slice(p+9,q),cdata:true,start:p,end:q+3};p=q+3;continue;}
  if(s.startsWith('<!--',p)){const q=s.indexOf('-->',p+4);if(q<0){if(tolerateTail)return;bad('XML_COMMENT');}if(s.slice(p+4,q).includes('--'))bad('XML_COMMENT');yield {kind:'comment',value:s.slice(p+4,q),start:p,end:q+3};p=q+3;continue;}
  let m=/^<(\/)?([A-Za-z_][\w.:-]*)((?:\s+[A-Za-z_][\w.:-]*\s*=\s*(?:"[^"<]*"|'[^'<]*'))*\s*)(\/?)>/.exec(s.slice(p));
  // Native card marker names may be Unicode, exclusively inside extra.
  if(!m&&path[0]==='reply'&&path[1]==='extra'&&path.length>=2)m=/^<(\/)?([\p{L}_][\p{L}\p{N}\p{M}_.:-]*)((?:\s+[A-Za-z_][\w.:-]*\s*=\s*(?:"[^"<]*"|'[^'<]*'))*\s*)(\/?)>/u.exec(s.slice(p));
  if(!m){if(tolerateTail&&s.indexOf('>',p)<0)return;bad('XML_TAG');}
  if(m[1]&&(m[3].trim()||m[4]))bad('XML_CLOSE');
  const attrs={};for(const a of m[3].matchAll(/([A-Za-z_][\w.:-]*)\s*=\s*(["'])(.*?)\2/g)){if(Object.hasOwn(attrs,a[1]))bad('XML_ATTRIBUTE_DUPLICATE');attrs[a[1]]=unxml(a[3]);}
  if(m[1])path.pop();else if(!m[4])path.push(m[2]);
  yield {kind:m[1]?'close':'open',name:m[2],attrs,selfClose:!!m[4],start:p,end:p+m[0].length};p+=m[0].length;
 }
}
const escape=s=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const tag=t=>'<'+t.name+Object.entries(t.attrs).map(([k,v])=>' '+k+'="'+escape(v)+'"').join('')+(t.selfClose?'/':'')+'>';
const DISPLAY_BLOCKS=new Set(['body','extra']);
const DISPLAY_FORBIDDEN=new Set(['script','style','template','head','iframe','object','embed','link','meta','form','input','button','select','textarea']);
function displayTag(t){if(DISPLAY_FORBIDDEN.has(t.name.toLowerCase()))bad('DISPLAY_UNSAFE_TAG');return tag(t);}
// Only documented, closed protocol wrappers may precede the reply. Never
// search arbitrary prose for <reply>, and never interpret thought text as XML.
const LEADING_THOUGHTS=new Set(['think','thinking','world_thinking','character_mode','character_thinking']);
function replyRegion(source,{partial=false}={}){
 if(typeof source!=='string'||source.length>2000000)bad('SIZE');
 let p=0;const thoughts=[];
 function trivia(){while(p<source.length){const ws=/^\s+/.exec(source.slice(p));if(ws){p+=ws[0].length;continue;}if(source.startsWith('<!--',p)){const end=source.indexOf('-->',p+4);if(end<0||source.slice(p+4,end).includes('--'))bad('XML_COMMENT');p=end+3;continue;}break;}}
 function opening(){return /^<([A-Za-z_][\w.:-]*)(?:\s+[A-Za-z_][\w.:-]*\s*=\s*(?:"[^"<]*"|'[^'<]*'))*\s*>/.exec(source.slice(p));}
 function opaque(m){
  const name=m[1],begin=p,content=p+m[0].length;let depth=1,q=content;
  const tokens=new RegExp('<!--[\\s\\S]*?-->|<!\\[CDATA\\[[\\s\\S]*?\\]\\]>|<(/?)'+name+'(?=[\\s/>])(?:[^>"\\\']|"[^"]*"|\\\'[^\\\']*\\\')*>','g');tokens.lastIndex=q;
  for(let t;(t=tokens.exec(source));){if(t[0].startsWith('<!--')||t[0].startsWith('<!['))continue;if(t[1]){if(!new RegExp('^</'+name+'\\s*>$').test(t[0]))bad('WRAPPER_BOUNDARY');depth--;}else if(!t[0].endsWith('/>'))depth++;
   if(depth>64)bad('XML_DEPTH');if(!depth){p=tokens.lastIndex;return {name,text:source.slice(content,t.index),start:begin,end:p};}
  }bad('WRAPPER_INCOMPLETE');
 }
 trivia();
 for(let count=0;;count++){
  const m=opening();if(!m||!LEADING_THOUGHTS.has(m[1]))break;
  if(count>=64)bad('XML_DEPTH');thoughts.push(opaque(m));trivia();
 }
 let output=false;if(/^<output\s*>/.test(source.slice(p))){p+=/^<output\s*>/.exec(source.slice(p))[0].length;output=true;trivia();}
 if(!/^<reply\b/.test(source.slice(p)))bad('REPLY');
 const start=p;
 if(partial)return {source:source.slice(start),thoughts,wrapped:output};
 let depth=0,end=null;
 for(const t of xmlTokens(source.slice(start))){
  if(t.kind==='open'&&!t.selfClose)depth++;
  else if(t.kind==='close'){depth--;if(depth===0){if(t.name!=='reply')bad('XML_CLOSE');end=start+t.end;break;}}
 }
 if(end===null)bad('INCOMPLETE');p=end;trivia();
 if(output){const close=/^<\/output\s*>/.exec(source.slice(p));if(!close)bad('WRAPPER_BOUNDARY');p+=close[0].length;trivia();}
 const tail=opening();if(tail?.[1]==='narrative_close'){opaque(tail);trivia();}
 if(p!==source.length)bad('OUTSIDE');
 return {source:source.slice(start,end),thoughts,wrapped:output};
}
function isReplyMessage(source){try{return !!replyRegion(source,{partial:true});}catch(_){return false;}}
function readEnvelope(source,acceptId){
 source=replyRegion(source).source;
 const blocks=Object.create(null),attrs=Object.create(null),stack=[];let id=null,root=false,closed=false,current=null,index=0,names=null;
 const structured=new Set(['task','title','next','vars','actions']);
 // Structured data plus body/extra display markup retain child tags. Other
 // payload blocks stay text-only and must use CDATA for embedded source.
 for(const t of xmlTokens(source)){
  if(t.kind==='comment'){if(/填写|占位/.test(t.value))bad('PLACEHOLDER');if(current==='body')blocks.body+='<!--'+t.value+'-->';continue;}
  if(t.kind==='text'){
   if(current)blocks[current]+=current==='body'?(t.cdata?t.value:t.raw):structured.has(current)&&current!=='vars'&&stack.length>2?escape(t.value):t.value;
   else if(t.value.trim())bad('OUTSIDE');continue;
  }
  if(t.kind==='open'){
   if(!stack.length){if(root||closed||t.name!=='reply'||t.selfClose||Object.keys(t.attrs).length&&(Object.keys(t.attrs).join()!=='id'||!acceptId(t.attrs.id)))bad('REPLY');root=true;id=t.attrs.id??null;}
   else if(stack.length===1){if(index===3)names=t.name==='next'?XML_NAMES:LEGACY_NAMES;if(t.name!==(names||XML_NAMES)[index++])bad('BLOCK_ORDER');current=t.name;blocks[current]='';attrs[current]=t.attrs;}
   else {if(DISPLAY_BLOCKS.has(current))blocks[current]+=displayTag(t);else{if(!structured.has(current))bad('NESTED_BLOCK_'+current.toUpperCase());blocks[current]+=tag(t);}}
   stack.push(t.name);if(stack.length>64)bad('XML_DEPTH');if(t.selfClose){stack.pop();if(stack.length===1)current=null;}
  }else{if(stack.length>2)blocks[current]+='</'+t.name+'>';if(stack.pop()!==t.name)bad('XML_CLOSE');if(t.name==='reply')closed=true;if(stack.length<2)current=null;}
 }
 if(!closed||stack.length||index!==(names||XML_NAMES).length)bad('INCOMPLETE');
 const e={id,blocks,attrs};return names===XML_NAMES?require('./pipes-wire.cjs').projectEnvelope(e):require('./rows-wire.cjs').projectEnvelope(e);
}
// Generation IDs correlate a saved reply with one prepared request. Display
// reads an already stored message by its host message ID and full source, so
// its XML ID is opaque metadata, never a generation receipt or a DOM selector.
// Both paths retain the same envelope, block-order and markup validation.
function parseEnvelope(source){return readEnvelope(source,id=>/^[0-9a-f]{32}$/.test(id));}
function parseDisplayEnvelope(source){return readEnvelope(source,id=>typeof id==='string'&&id.trim().length>0);}
function extractXMLBody(source){
 source=replyRegion(source,{partial:true}).source;
 const bodyStack=[];let depth=0,inside=false,found=0,done=false,value='',root=false;
 for(const t of xmlTokens(source,{tolerateTail:true})){
  if(t.kind==='open'){
   if(depth===0&&t.name==='reply')root=true;
   if(root&&depth===1&&t.name==='body'){if(++found>1)bad('BODY_BOUNDARY');inside=true;if(t.selfClose){inside=false;done=true;}else bodyStack.push('body');}
   else if(inside){value+=displayTag(t);if(!t.selfClose)bodyStack.push(t.name);}
   if(!t.selfClose)depth++;
  }else if(t.kind==='close'){
   if(inside){if(bodyStack.at(-1)!==t.name)bad('XML_CLOSE');if(bodyStack.length===1){inside=false;done=true;}else value+='</'+t.name+'>';bodyStack.pop();}
   depth--;if(root&&depth===0&&t.name==='reply')break;
  }else if(t.kind==='text'&&inside)value+=t.cdata?t.value:t.raw;
  else if(t.kind==='comment'&&inside)value+='<!--'+t.value+'-->';
 }
 if(found!==1||!done||inside)bad('BODY_BOUNDARY');return value;
}
function replyGenerationId(source){try{source=replyRegion(source,{partial:true}).source;return /^\s*<reply\s+id\s*=\s*(["'])([0-9a-f]{32})\1\s*>/.exec(source)?.[2]||null;}catch(_){return null;}}
module.exports={replyRegion,isReplyMessage,xmlTokens,escapeBareAmpersands,XML_NAMES,LEGACY_NAMES,parseEnvelope,parseDisplayEnvelope,extractXMLBody,replyGenerationId};

},{"./pipes-wire.cjs":"pipes-wire.cjs","./rows-wire.cjs":"rows-wire.cjs"}]
};
const foundationCache=new Map();
function foundationRequire(id){
 if(foundationCache.has(id))return foundationCache.get(id).exports;
 const entry=foundationModules[id];if(!entry)throw Error('Unknown Foundation module');
 const module={exports:{}};foundationCache.set(id,module);
 entry[0](module,module.exports,name=>{if(!Object.hasOwn(entry[1],name))throw Error('Unknown Foundation dependency');return foundationRequire(entry[1][name]);});
 return module.exports;
}
export const {isReplyMessage,extractXMLBody,parseDisplayEnvelope}=foundationRequire('xml-envelope.cjs');
export const {projectJourney}=foundationRequire('journey-reader.cjs');
export const {countBody}=foundationRequire('body-count.cjs');
export const {read:readParagraphs}=foundationRequire('numbered-paragraphs.cjs');
export const {strictJSON}=foundationRequire('strict-json.cjs');
