import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {Window} from 'happy-dom';import {mountLayout,installComposer} from '../layout.js';import {mountMessageNavigation} from '../navigation.js';
const css=await readFile(new URL('../shell.css',import.meta.url),'utf8');
// Original theme rule reported in the device failure. Load it last as user CSS
// can follow extension CSS; verify the editor's size contract still wins.
const legacyTheme='#chat .mes_edit_buttons .menu_button{width:auto!important;min-width:38px;min-height:36px;height:auto!important;padding:8px 10px!important;white-space:normal}';
function setup(editing){const w=new Window(),d=w.document;d.head.innerHTML='<style>.mes_edit_buttons{display:none}.ch_name{display:flex}</style><style>'+css+'</style>';d.body.className='tisya-active';d.body.innerHTML='<div id="chat"><div class="mes"><div class="mes_block"><div class="ch_name"><div class="mes_header_info">角色</div><div class="mes_buttons">原生菜单</div><div class="mes_edit_buttons">'+['done','copy','add_reasoning','delete','up','down','cancel'].map(x=>'<div class="mes_edit_'+x+' menu_button"></div>').join('')+'</div></div><div class="mes_text">'+(editing?'<textarea class="edit_textarea">长篇草稿</textarea>':'正文')+'</div><div class="mes_media_wrapper"></div><div class="tisya-actions">消息操作</div></div></div></div>';return {w,d,style:selector=>w.getComputedStyle(d.querySelector(selector))};}
test('edit toolbar is a sticky final flex item while its native header parent and all handlers survive',async()=>{const f=setup(true);f.d.querySelector('.mes_text').classList.add('tisya-source-concealed');assert.equal(f.style('.mes_text').display,'block');const buttons=f.d.querySelector('.mes_edit_buttons'),header=buttons.parentElement,save=buttons.querySelector('.mes_edit_done'),cancel=buttons.querySelector('.mes_edit_cancel');let saved=0,cancelled=0;save.addEventListener('click',()=>saved++);cancel.addEventListener('click',()=>cancelled++);
 assert.equal(f.style('.mes_block').display,'flex');assert.equal(f.style('.ch_name').display,'contents');assert.equal(f.style('.mes_edit_buttons').position,'sticky');assert.equal(f.style('.mes_edit_buttons').bottom,'0px');assert.equal(f.style('.mes_edit_buttons').order,'50');assert.equal(f.style('.mes_edit_done').order,'0');assert.equal(f.style('.mes_edit_cancel').order,'1');assert.equal(f.style('.mes_edit_buttons').flexFlow,'row nowrap');assert.equal(f.style('.tisya-actions').display,'none');assert.equal(buttons.parentElement,header);assert.equal(f.d.querySelectorAll('.mes_edit_done').length,1);save.click();cancel.click();assert.equal(saved,1);assert.equal(cancelled,1);assert.equal(f.d.querySelector('.edit_textarea').value,'长篇草稿');await f.w.happyDOM.abort();});
test('non-editing messages retain native hidden edit toolbar and ordinary message flow',async()=>{const f=setup(false);assert.equal(f.style('.mes_edit_buttons').display,'none');assert.equal(f.style('.ch_name').display,'flex');assert.notEqual(f.style('.tisya-actions').display,'none');await f.w.happyDOM.abort();});
test('legacy automatic height and inherited tall toolbar cannot stretch editor controls',async()=>{
 const f=setup(true),style=f.d.createElement('style');style.textContent=legacyTheme;f.d.head.append(style);const toolbar=f.d.querySelector('.mes_edit_buttons');toolbar.style.height='1100px';
 assert.equal(f.style('.mes_edit_buttons').height,'54px');assert.equal(f.style('.mes_edit_buttons').maxHeight,'54px');assert.equal(f.style('.mes_edit_buttons').alignItems,'center');
 for(const button of toolbar.children){const s=f.w.getComputedStyle(button);assert.equal(s.height,'44px');assert.equal(s.maxHeight,'44px');assert.equal(s.whiteSpace,'nowrap');}
 assert.equal(f.style('.mes_edit_done').width,'72px');assert.equal(f.style('.mes_edit_cancel').width,'72px');await f.w.happyDOM.abort();
});
test('new shortcut rail preserves native parents and the menu precedes the textarea in bottom-row DOM order',async()=>{const w=new Window(),d=w.document;d.head.innerHTML='<style>'+css+'</style>';d.body.innerHTML='<div id="top-settings-holder"></div><div id="sheld"><div id="chat"></div></div><div id="nonQRFormItems"><div id="leftSendForm"><div id="options_button" class="interactable"></div><div id="extensionsMenuButton" class="interactable"></div></div><textarea id="send_textarea"></textarea><div id="rightSendForm"><button id="ttas_agent_send_toggle"></button><button id="send_but"></button></div></div>';const left=d.querySelector('#leftSendForm'),right=d.querySelector('#rightSendForm'),layout=mountLayout(d),dispose=installComposer(d),nav=mountMessageNavigation(d);
 assert.equal(d.querySelector('#nonQRFormItems').firstElementChild.id,'tisya-menu-trigger');assert.equal(w.getComputedStyle(left).display,'flex');assert.equal(w.getComputedStyle(left).overflowX,'auto');assert.equal(w.getComputedStyle(left).flexFlow,'row nowrap');for(const id of ['tisya-attach','tisya-previous-message','tisya-next-message','tisya-bottom-message','options_button','extensionsMenuButton'])assert.equal(d.getElementById(id).parentElement,left);assert.equal(d.querySelector('#ttas_agent_send_toggle').parentElement,right);assert.equal(d.querySelector('#send_but').parentElement,right);assert.equal(w.getComputedStyle(d.querySelector('#send_textarea')).gridColumn,'2/6');nav.dispose();dispose();layout.dispose();await w.happyDOM.abort();});
