import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {Window} from 'happy-dom';import * as model from '../model.js';
async function setup(){const w=new Window({url:'http://localhost'});w.document.body.innerHTML='<div id="top-settings-holder">'+Array.from({length:9},(_,i)=>`<div class="drawer"><div class="drawer-toggle"><i class="drawer-icon" title="${i}"></i></div><div class="drawer-content closedDrawer"></div></div>`).join('')+'</div><div id="chat"><div class="mes" mesid="0"><div class="mes_block"><div class="mes_text">正文</div><div class="mes_buttons"><button class="mes_edit">edit</button><button class="mes_create_branch">branch</button><div class="extraMesButtonsHint"></div></div></div></div></div><textarea id="send_textarea"></textarea><button id="option_regenerate"></button><button id="options_button"></button>';
w.structuredClone=structuredClone;w.fetch=async(url,options)=>({ok:true,json:async()=>[{file_name:JSON.parse(options.body).avatar_url+'.jsonl',mes:'已保存正文'}]});const errors=[],handlers={};const ctx={chat:[{mes:'正文',is_user:false}],characters:[{avatar:'a.png',name:'同名',chat:'a',tags:['悬疑']},{avatar:'b.png',name:'同名',chat:'b',tags:['日常']}],extensionSettings:{},getRequestHeaders:()=>({}),getCurrentChatId:()=> 'a',eventTypes:{APP_READY:'ready',CHAT_CHANGED:'chat'},eventSource:{on:(e,f)=>{handlers[e]=f},removeListener:()=>{}},saveSettingsDebounced:()=>{},mainApi:'openai'};let generating=false,generated=[];w.fixture={getContext:()=>ctx,isGenerating:()=>generating,Generate:async(...args)=>{generated.push(args)},getAgentGenerationOptions:async()=>({}),hasActiveAgentRun:()=>false,loadReadingFont:async()=>{},...model};w.toastr={error:t=>errors.push(t)};
let code=await readFile(new URL('../index.js',import.meta.url),'utf8');code=code.replace(/^import \{([^}]+)\} from '[^']+';/gm,(_,names)=>`const {${names}}=window.fixture;`).replace('export function registerChatSurface','function registerChatSurface');w.eval(code);handlers.ready();await w.happyDOM.whenAsyncComplete();return {w,ctx,errors,generated,setGenerating:v=>generating=v};}
async function click(f,a){f.w.document.querySelector(`[data-tisya-action="${a}"]`).click();await f.w.happyDOM.whenAsyncComplete();}
test('contacts, labels, grouping and teardown keep native nodes',async()=>{const f=await setup();const native=f.w.document.querySelector('.mes_text');await click(f,'contacts');assert.equal(f.w.document.querySelectorAll('.tisya-contact').length,2);await click(f,'group:0');f.w.document.querySelector('#tisya-group-name').value='世界卡';await click(f,'save-group:a.png');assert.deepEqual(f.errors,[]);assert.equal(f.ctx.extensionSettings.缇斯亚界面.联系人分组['a.png'],'世界卡');await click(f,'menu');assert.match(f.w.document.querySelector('[data-tisya-action="drawer:5"]').textContent,/背景/);await click(f,'disable');assert.equal(f.w.document.querySelector('#tisya-shell'),null);assert.equal(f.w.document.querySelectorAll('.tisya-actions').length,0);assert.equal(f.w.document.querySelector('.mes_text'),native);assert.deepEqual(f.errors,[]);f.w.happyDOM.abort();});
test('continue requests next normal response, never submits composer draft',async()=>{const f=await setup();f.w.document.querySelector('#send_textarea').value='未发送草稿';await click(f,'next');assert.equal(f.generated.length,0);assert.match(f.errors.at(-1),/草稿/);f.w.document.querySelector('#send_textarea').value='';await click(f,'next');assert.equal(f.generated.length,1);assert.equal(f.generated[0][0],'normal');assert.equal(f.generated[0][1].automatic_trigger,true);f.w.happyDOM.abort();});
test('message menu refuses edited source and generation blocks editing',async()=>{const f=await setup();let edits=0;f.w.document.querySelector('.mes_edit').addEventListener('click',()=>edits++);await click(f,'more');f.ctx.chat[0].mes='变化';await click(f,'msg-edit');assert.equal(edits,0);assert.match(f.errors.at(-1),/变化/);f.ctx.chat[0].mes='正文';await click(f,'close');await click(f,'more');f.setGenerating(true);await click(f,'msg-edit');assert.equal(edits,0);assert.match(f.errors.at(-1),/生成/);f.w.happyDOM.abort();});

test('home lists every persisted chat and keeps same-name contacts separate',async()=>{const f=await setup();assert.equal(f.w.document.querySelectorAll('[data-home-chat]').length,2);assert.match(f.w.document.querySelector('[data-home-card="0"]').textContent,/a.png/);assert.match(f.w.document.querySelector('[data-home-card="1"]').textContent,/b.png/);f.w.fetch=async()=>{throw new Error('连接失败')};await click(f,'home');assert.equal(f.w.document.querySelectorAll('[role="alert"]').length,2);assert.equal(f.w.document.querySelectorAll('[data-home-chat]').length,0);f.w.happyDOM.abort();});
