import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {Window} from 'happy-dom';
import {mountMessageVisual,mountMessageAppearance,mountChatEffects} from '../message-ui.js';import {mountPet,petBounds} from '../pet.js';import {composition} from '../visual-core.js';import {visualAssets,phoneResources,journeyArt,motionManifest} from '../visual-assets.js';import {fixture} from './fixtures/journey-r4.cjs';
const format=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;');
function setup(){const w=new Window({url:'http://localhost',settings:{disableCSSFileLoading:true,disableJavaScriptFileLoading:true}}),d=w.document;d.body.innerHTML='<div id="sheld"><div id="chat"><div class="mes" mesid="0"><div class="mes_block"><div class="mes_text">native source</div><button class="mes_edit">edit</button></div></div></div><form id="send_form"></form></div>';
 w.matchMedia=()=>({matches:true,addEventListener(){},removeEventListener(){}});w.IntersectionObserver=class{observe(){}disconnect(){}};const dims=new Map(Object.entries(phoneResources).map(([k,r])=>[visualAssets[k],[r.width,r.height]]));for(const r of Object.values(motionManifest))dims.set(visualAssets[r.file],[r.cellWidth*r.columns,r.cellHeight*r.rows]);
 w.Image=class{set src(s){this.url=s;const r=dims.get(s)??[1,1];this.naturalWidth=this.width=r[0];this.naturalHeight=this.height=r[1];}decode(){return Promise.resolve();}};
 const ctx=new Proxy({createRadialGradient:()=>({addColorStop(){}})}, {get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>{o[k]=v;return true;}});w.HTMLCanvasElement.prototype.getContext=()=>ctx;
 Object.defineProperty(w,'innerWidth',{value:360,writable:true});Object.defineProperty(w,'innerHeight',{value:760,writable:true});const r=(x,y,width,height)=>({x,y,left:x,top:y,width,height,right:x+width,bottom:y+height});d.querySelector('#chat').getBoundingClientRect=()=>r(0,24,w.innerWidth,600);d.querySelector('#send_form').getBoundingClientRect=()=>r(0,624,w.innerWidth,110);d.querySelector('#sheld').getBoundingClientRect=()=>r(0,24,w.innerWidth,712);return {w,d,node:d.querySelector('.mes')};}
const flush=async()=>{for(let i=0;i<90;i++)await Promise.resolve();};
test('all approved art references resolve locally, including cropped frame pieces',async()=>{for(const url of Object.values(visualAssets))assert.ok((await readFile(new URL(url))).length);for(const row of Object.values(journeyArt.pieces))for(const p of row.crops)assert.ok(visualAssets[p.key]);});
test('message skin contains public body, original ornaments and five journey tabs without private task text',async()=>{const {w,d,node}=setup(),source=fixture(),chosen=[];const view=mountMessageVisual(d,node,{source,name:'月潮',formatBody:format,onChooseAction:t=>chosen.push(t)}),root=view.host.shadowRoot;
 assert.match(root.querySelector('.story').textContent,/./);assert.equal(root.querySelectorAll('.pendant-pearl').length,2);assert.equal(root.querySelectorAll('.visual-creature').length,2);assert.equal(root.querySelectorAll('.jr-nav button').length,5);assert.equal(root.querySelectorAll('.action').length,4);assert.equal(root.querySelector('#task-content'),null);assert.equal(root.querySelector('#next-content'),null);assert.ok(!root.textContent.includes('<task'));
 root.querySelector('.action').click();assert.equal(chosen[0],'察看门锁');const pearl=root.querySelector('#journey-toggle');pearl.click();assert.equal(pearl.getAttribute('aria-expanded'),'true');assert.equal(root.querySelector('.journey-region').hidden,false);root.querySelector('[data-jr-tab="more"]').click();root.querySelector('.jr-theme-choice').click();assert.equal(root.querySelector('.journey-reader').dataset.theme,'day');pearl.click();assert.equal(root.querySelector('.journey-region').hidden,true);view.dispose();assert.equal(node.querySelector('.tisya-message-visual'),null);await w.happyDOM.abort();});
test('malformed envelopes never render task or audit data as body',async()=>{const {w,d,node}=setup();const view=mountMessageVisual(d,node,{source:'<reply><task>PRIVATE_CANARY</task>',formatBody:format,onChooseAction(){}});assert.ok(!view.host.shadowRoot.textContent.includes('PRIVATE_CANARY'));assert.equal(view.host.shadowRoot.querySelectorAll('.action').length,0);view.dispose();await w.happyDOM.abort();});
test('native message node/listeners survive projection, edit and teardown; stale buttons become inert',async()=>{const {w,d,node}=setup(),native=node.querySelector('.mes_text'),message={mes:fixture(),name:'月潮'},source=message.mes,chosen=[];let taps=0;native.addEventListener('click',()=>taps++);const ui=mountMessageAppearance(d,{getMessage:()=>message,formatBody:format,onChooseAction:(n,s,t)=>chosen.push([s,t]),getMotion:()=>false});ui.sync(node);const old=node.querySelector('.tisya-message-visual'),action=old.shadowRoot.querySelector('.action');assert.equal(native.classList.contains('tisya-source-concealed'),true);ui.sync(node);assert.equal(node.querySelector('.tisya-message-visual'),old);
 message.mes='普通的下一条正文';ui.sync(node,{pending:true});assert.equal(node.querySelector('.tisya-message-visual'),old);ui.sync(node);action.click();assert.equal(chosen.length,0);assert.equal(message.mes,'普通的下一条正文');node.classList.add('editing');ui.sync(node);assert.equal(ui.size(),0);assert.equal(native.classList.contains('tisya-source-concealed'),false);assert.equal(node.querySelector('.mes_text'),native);native.click();assert.equal(taps,1);node.classList.remove('editing');message.mes=source;ui.sync(node);ui.dispose();assert.equal(native.classList.contains('tisya-source-concealed'),false);assert.equal(node.querySelector('.mes_text'),native);await w.happyDOM.abort();});
test('native interactive cards retain their owned content',async()=>{const {w,d,node}=setup(),native=node.querySelector('.mes_text');native.innerHTML='<iframe title="card"></iframe>';const ui=mountMessageAppearance(d,{getMessage:()=>({mes:'A native card'}),formatBody:format,onChooseAction(){}});ui.sync(node);assert.equal(ui.size(),0);assert.equal(native.classList.contains('tisya-source-concealed'),false);ui.dispose();await w.happyDOM.abort();});
test('detached messages release presentations',async()=>{const {w,d,node}=setup();const ui=mountMessageAppearance(d,{getMessage:()=>({mes:fixture()}),formatBody:format,onChooseAction(){},getMotion:()=>false});ui.sync(node);node.remove();await flush();assert.equal(ui.size(),0);ui.dispose();await w.happyDOM.abort();});
test('phone uses original composition, application placeholders, close and restore without duplicating instances',async()=>{const {w,d}=setup(),errors=[],pet=mountPet(d,{onError:e=>errors.push(e.message)});await flush();assert.equal(pet.report().ready,true);assert.equal(pet.report().mode,'standing');const root=d.querySelector('#tisya-pet').shadowRoot;root.querySelector('[data-action="open"]').click();await flush();assert.equal(pet.report().mode,'folded');root.querySelector('[data-action="expand"]').click();await flush();assert.equal(pet.report().mode,'expanded');assert.deepEqual(pet.report().geometry,composition('expanded',360));assert.equal(root.querySelectorAll('.app').length,12);root.querySelector('.app[aria-label="图鉴"]').click();await flush();assert.match(root.querySelector('.app-page').textContent,/后续版本接入/);root.querySelector('[data-action="home"]').click();assert.equal(root.querySelector('.app-page'),null);root.querySelector('[data-action="close"]').click();await flush();assert.equal(pet.report().mode,'standing');root.querySelector('.hide').click();assert.equal(d.querySelector('#tisya-pet').hidden,true);pet.setVisible(true);assert.equal(d.querySelector('#tisya-pet').hidden,false);assert.equal(d.querySelectorAll('#tisya-pet').length,1);pet.dispose();assert.equal(d.querySelector('#tisya-pet'),null);assert.deepEqual(errors,[]);await w.happyDOM.abort();});
test('small viewport and keyboard clamp the phone viewport without scaling artwork or changing composer',async()=>{const {w,d}=setup(),form=d.querySelector('#send_form'),pet=mountPet(d);w.innerWidth=320;pet.setMode('expanded');await flush();const report=pet.report(),host=d.querySelector('#tisya-pet');assert.equal(report.geometry.width,composition('expanded',360).width);assert.ok(parseFloat(host.style.left)>=4);assert.ok(parseFloat(host.style.left)+parseFloat(host.style.width)<=316);assert.equal(d.querySelector('#send_form'),form);w.innerHeight=300;w.dispatchEvent(new w.Event('resize'));assert.ok(parseFloat(host.style.height)<=272);assert.equal(pet.report().mode,'expanded');assert.equal(host.shadowRoot.querySelector('.viewport').style.transform,'');pet.dispose();await w.happyDOM.abort();});
test('drag clamps position and consumes the following click instead of opening phone',async()=>{const {w,d}=setup(),pet=mountPet(d);await flush();const root=d.querySelector('#tisya-pet').shadowRoot,b=root.querySelector('[data-action="open"]');const p=(type,x,y)=>b.dispatchEvent(new w.PointerEvent(type,{bubbles:true,pointerId:1,button:0,clientX:x,clientY:y}));p('pointerdown',200,200);p('pointermove',-500,-500);p('pointerup',-500,-500);b.click();assert.equal(pet.report().mode,'standing');assert.equal(pet.report().position.x,petBounds(d).x);pet.dispose();await w.happyDOM.abort();});
test('background remains pointer transparent and disposes without altering chat geometry',async()=>{const {w,d}=setup(),chat=d.querySelector('#chat'),before=chat.style.cssText;const effects=mountChatEffects(d,{getMotion:()=>false});await flush();assert.equal(d.querySelector('#tisya-chat-effects').getAttribute('aria-hidden'),'true');assert.equal(chat.style.cssText,before);effects.dispose();assert.equal(d.querySelector('#tisya-chat-effects'),null);assert.equal(chat.style.cssText,before);await w.happyDOM.abort();});


test('message observer settles after projection instead of rewriting unchanged class attributes',async()=>{
 const {w,d,node}=setup();const ui=mountMessageAppearance(d,{getMessage:()=>({mes:fixture()}),formatBody:format,onChooseAction(){},getMotion:()=>false});ui.sync(node);await w.happyDOM.whenAsyncComplete();const old=node.querySelector('.tisya-message-visual');let changes=0;const observer=new w.MutationObserver(records=>{changes+=records.length;});observer.observe(node,{attributes:true,subtree:true});for(let i=0;i<4;i++)ui.sync(node);await w.happyDOM.whenAsyncComplete();assert.equal(changes,0);assert.equal(node.querySelector('.tisya-message-visual'),old);observer.disconnect();ui.dispose();await w.happyDOM.abort();
});
